package langgraph

import (
	_ "embed"
	"fmt"
	"strings"

	"github.com/thakee/orca/compiler/analyzer"
	"github.com/thakee/orca/compiler/codegen"
	"github.com/thakee/orca/compiler/codegen/python"
	"github.com/thakee/orca/compiler/token"
)

//go:embed orca.py
var orcaRuntime string

// orcaPrefix is the namespace prefix for all Orca runtime symbols in generated
// Python code. Block constructors become __orca_model(), __orca_agent(), etc.
// GraphState trigger fields become __orca_trigger, __orca_payload.
const orcaPrefix = "__orca_"

// LangGraphBackend generates Python/LangGraph code directly from the analyzed AST.
type LangGraphBackend struct {
	codegen.BaseBackend
	resolvedProviders resolvedProviders
	resolvedTools     map[string]resolvedToolInvoke // keyed by tool block name
}

// New creates a new LangGraph codegen backend for the given analyzed AST.
func New(program *analyzer.AnalyzedProgram) codegen.CodegenBackend {
	return &LangGraphBackend{BaseBackend: codegen.BaseBackend{Program: *program}}
}

// Generate produces a tree-structured output targeting LangGraph.
func (b *LangGraphBackend) Generate() codegen.CodegenOutput {

	b.resolveProviders()
	b.resolveToolInvokes()

	return codegen.CodegenOutput{
		BackendType: codegen.BackendLangGraph,
		RootDir: codegen.OutputDirectory{
			Name: "build",
			Files: []codegen.OutputFile{
				{Name: "main.py", Content: b.generateMain()},
			},
		},
		Dependencies: dependenciesFromProviders(b.resolvedProviders),
		Diagnostics:  b.Program.Diagnostics,
	}
}

func (b *LangGraphBackend) generateMain() string {
	var s strings.Builder

	s.WriteString("# Auto-generated by Orca compiler — do not edit\n")

	workflows := b.collectWorkflows()
	allImports := append(b.resolvedProviders.providerImports, b.toolImports()...)
	allImports = append(allImports, workflowImports(workflows)...)
	b.writeImports(&s, allImports)

	// Inline the Orca runtime functions.
	s.WriteString("\n")
	s.WriteString(orcaRuntime)
	s.WriteString("\n")

	b.writeOrcaBlockSection(&s, "Schemas", token.BlockSchema)
	b.writeOrcaBlockSection(&s, "Inputs", token.BlockInput)
	b.writeOrcaBlockSection(&s, "Variables", token.BlockLet)
	b.writeOrcaBlockSection(&s, "Models", token.BlockModel)
	b.writeOrcaBlockSection(&s, "Knowledge", token.BlockKnowledge)
	b.writeToolSection(&s)
	b.writeGraphState(&s)
	b.writeOrcaBlockSection(&s, "Agents", token.BlockAgent)
	b.writeOrcaBlockSection(&s, "Cron", token.BlockCron)
	b.writeOrcaBlockSection(&s, "Webhooks", token.BlockWebhook)
	b.writeWorkflowSection(&s, workflows)

	return s.String()
}

// writeImports emits import statements: TypedDict plus each resolved provider import.
func (b *LangGraphBackend) writeImports(s *strings.Builder, providerImports []python.PythonImport) {

	// TODO: we need to build the dependency list of python while analyzing the ast
	// And dump all here instead of hardcoding it here.
	s.WriteString(python.PythonImport{
		Module:     "typing",
		Package:    "",
		FromImport: true,
		Symbols:    []python.ImportSymbol{{Name: "TypedDict"}},
	}.Source())
	s.WriteString("\n")

	for _, imp := range providerImports {
		s.WriteString("\n")
		s.WriteString(imp.Source())
		s.WriteString("\n")
	}
}

// writeOrcaBlockSection emits all top-level blocks of the given kind as
// `name = __orca_<kind>(...)` under "# --- <sectionTitle> ---". Skips the section when empty.
func (b *LangGraphBackend) writeOrcaBlockSection(s *strings.Builder, sectionTitle string, kind token.BlockKind) {
	blocks := b.CollectBlocksByKind(kind)
	if len(blocks) == 0 {
		return
	}
	s.WriteString("\n# --- " + sectionTitle + " ---\n")
	for _, block := range blocks {
		if block == nil {
			panic("BUG: writeOrcaBlockSection collected nil block")
		}
		s.WriteString("\n")
		fmt.Fprintf(s, "%s = %s\n", block.Name, topLevelBlockSource(block))
	}
}

func (b *LangGraphBackend) writeGraphState(s *strings.Builder) {
	s.WriteString("\n# --- Graph State ---\n")
	s.WriteString("class GraphState(TypedDict):\n")
	fmt.Fprintf(s, "    %strigger: str | None\n", orcaPrefix)
	fmt.Fprintf(s, "    %spayload: dict | None\n", orcaPrefix)
}
