package langgraph

import (
	_ "embed"
	"fmt"
	"strings"

	"github.com/thakee/orca/compiler/analyzer"
	"github.com/thakee/orca/compiler/ast"
	"github.com/thakee/orca/compiler/codegen"
	"github.com/thakee/orca/compiler/codegen/python"
	"github.com/thakee/orca/compiler/types"
	"github.com/thakee/orca/compiler/workflow"
)

//go:embed runtime.py
var embeddedRuntime string

// LangGraphBackend generates Python/LangGraph code directly from the analyzed AST.
type LangGraphBackend struct {
	codegen.BaseBackend
	resolvedProviders resolvedProviders
	resolvedTools     map[string]resolvedToolInvoke        // keyed by tool block name
	resolvedWorkflows map[string]workflow.ResolvedWorkflow // keyed by workflow block name
}

// New creates a new LangGraph codegen backend for the given analyzed AST.
func New(program *analyzer.AnalyzedProgram) codegen.CodegenBackend {
	return &LangGraphBackend{BaseBackend: codegen.BaseBackend{Program: *program}}
}

// Generate produces a tree-structured output targeting LangGraph.
func (b *LangGraphBackend) Generate() codegen.CodegenOutput {

	b.resolveProviders()
	b.resolveToolInvokes()
	b.resolveWorkflows()

	workflows := b.collectWorkflows()
	hasWorkflows := len(workflows) > 0
	deps := dependenciesFromProviders(b.resolvedProviders, hasWorkflows)

	return codegen.CodegenOutput{
		BackendType: codegen.BackendLangGraph,
		RootDir: codegen.OutputDirectory{
			Name: "build",
			Files: []codegen.OutputFile{
				{Name: "main.py", Content: b.generateMain()},
				{Name: "pyproject.toml", Content: pyprojectToml(deps)},
			},
		},
		Dependencies: deps,
		Diagnostics:  b.Program.Diagnostics,
	}
}

func (b *LangGraphBackend) generateMain() string {
	var s strings.Builder

	s.WriteString("# Auto-generated by Orca compiler — do not edit\n")
	s.WriteString("\"\"\"Orca runtime — inlined into generated main.py.\n\n")
	s.WriteString("These functions are called by generated code to create block instances.\n")
	s.WriteString("All public names are prefixed with __orca_ to avoid collisions with user code.\n")
	s.WriteString("\"\"\"\n\n")
	s.WriteString("from __future__ import annotations\n\n")

	workflows := b.collectWorkflows()
	schemaBlocks := b.CollectBlocksByKind(types.BlockKindSchema)
	allImports := append(b.resolvedProviders.providerImports, b.toolImports()...)
	allImports = append(allImports, workflowImports(workflows)...)
	allImports = append(allImports, python.PythonImport{Module: "sys"})

	if len(schemaBlocks) > 0 {
		allImports = append(allImports, python.SchemaImport())
	}
	b.writeImports(&s, allImports)

	// Inline the Orca runtime functions.
	s.WriteString("\n")
	s.WriteString(embeddedRuntime)
	s.WriteString("\n")

	b.writeSchemaSection(&s, schemaBlocks)
	b.writeBlocksInOrder(&s)

	b.writeWorkflowEntrypoint(&s)

	return s.String()
}

// writeImports emits import statements: TypedDict plus each resolved provider import.
func (b *LangGraphBackend) writeImports(s *strings.Builder, providerImports []python.PythonImport) {
	for _, imp := range providerImports {
		s.WriteString(imp.Source())
		s.WriteString("\n")
	}
}

// writeBlocksInOrder emits all user-defined blocks in topological dependency
// order (from AnalyzedProgram.BlockOrder).
func (b *LangGraphBackend) writeBlocksInOrder(s *strings.Builder) {
	for _, name := range b.Program.BlockOrder {
		block := b.BlockByName(name)
		if block == nil {
			continue
		}

		// Skip schema blocks — they're handled separately.
		if block.Kind == types.BlockKindSchema {
			continue
		}

		b.writeBlock(s, block)
	}
}

// writeBlock emits a single block, dispatching to the appropriate writer
// based on block kind.
func (b *LangGraphBackend) writeBlock(s *strings.Builder, block *ast.BlockStatement) {
	switch block.Kind {
	case analyzer.BlockKindModel:
		s.WriteString("\n")
		fmt.Fprintf(s, "%s = %s\n", block.Name, modelBlockSource(block))

	case analyzer.BlockKindTool:
		resolved, ok := b.resolvedTools[block.Name]
		if !ok {
			s.WriteString("\n")
			fmt.Fprintf(s, "%s = %s\n", block.Name, topLevelBlockSource(block))
			return
		}
		if resolved.verbatim != "" {
			s.WriteString("\n")
			s.WriteString(resolved.verbatim)
			s.WriteString("\n")
		}
		s.WriteString("\n")
		fmt.Fprintf(s, "%s = %s\n", block.Name, toolBlockSource(block, resolved.invokeRef))

	case analyzer.BlockKindWorkflow:
		if rw, ok := b.resolvedWorkflows[block.Name]; ok {
			if len(rw.Nodes) > 0 {
				b.writeWorkflow(s, rw)
			}
		}

	default:
		// Generic block: let, agent, knowledge, cron, webhook.
		s.WriteString("\n")
		fmt.Fprintf(s, "%s = %s\n", block.Name, topLevelBlockSource(block))
	}
}

// writeSchemaSection emits Pydantic BaseModel classes for all schema blocks.
// Each schema block becomes a class with typed fields and optional Field() descriptors.
func (b *LangGraphBackend) writeSchemaSection(s *strings.Builder, blocks []*ast.BlockStatement) {
	if len(blocks) == 0 {
		return
	}
	s.WriteString("\n")
	for _, block := range blocks {
		s.WriteString("\n")
		s.WriteString(python.SchemaBlockToSource(block))
	}
}
