package langgraph

import (
	"fmt"
	"strings"

	"github.com/thakee/orca/compiler/analyzer"
	"github.com/thakee/orca/compiler/ast"
	"github.com/thakee/orca/compiler/codegen"
	"github.com/thakee/orca/compiler/codegen/python"
	"github.com/thakee/orca/compiler/diagnostic"
	"github.com/thakee/orca/compiler/token"
)

// LangGraphBackend generates Python/LangGraph code directly from the analyzed AST.
type LangGraphBackend struct {
	codegen.BaseBackend
}

// New creates a new LangGraph codegen backend for the given analyzed AST.
func New(program *analyzer.AnalyzedProgram) codegen.CodegenBackend {
	return &LangGraphBackend{BaseBackend: codegen.BaseBackend{Program: *program}}
}

// Generate produces a tree-structured output targeting LangGraph.
func (b *LangGraphBackend) Generate() codegen.CodegenOutput {

	rp := b.resolveProviders()

	return codegen.CodegenOutput{
		BackendType: codegen.BackendLangGraph,
		RootDir: codegen.OutputDirectory{
			Name: "build",
			Files: []codegen.OutputFile{
				{Name: "main.py", Content: b.generateMain(rp.providers)},
			},
		},
		Dependencies: rp.dependencies,
		Diagnostics:  b.Program.Diagnostics,
	}
}

func (b *LangGraphBackend) generateMain(providerNames []string) string {
	var s strings.Builder

	s.WriteString("# Auto-generated by Orca compiler — do not edit\n")

	b.writeImports(&s, providerNames)
	b.writeVars(&s)
	b.writeModels(&s)
	b.writeGraphState(&s)
	b.writeAgents(&s)

	return s.String()
}

// writeImports emits import statements for known providers.
func (b *LangGraphBackend) writeImports(s *strings.Builder, providers []string) {

	// TODO: Implement Import nodes in python.go and resolve dependency properly.
	s.WriteString("from typing import TypedDict\n")

	if len(b.CollectBlocks(token.AGENT)) > 0 {
		s.WriteString("from langgraph.prebuilt import create_react_agent\n")
	}

	for _, p := range providers {
		if info, ok := providerRegistry[p]; ok {
			s.WriteString("\n")
			s.WriteString(info.Import)
			s.WriteString("\n")
		}
	}
}

// writeVars emits top-level let bindings as Python assignments under "# --- Variables ---".
func (b *LangGraphBackend) writeVars(s *strings.Builder) {
	lets := b.CollectLets()
	if len(lets) == 0 {
		return
	}
	s.WriteString("\n# --- Variables ---\n")
	for _, block := range lets {
		for _, assign := range block.Assignments {
			s.WriteString("\n")
			fmt.Fprintf(s, "%s = %s  # %s\n",
				assign.Name,
				python.OrcaToPythonExpression(assign.Value),
				codegen.SourceComment(block.SourceFile, assign.TokenStart.Line))
		}
	}
}

// writeModels emits model block instantiations under "# --- Models ---".
func (b *LangGraphBackend) writeModels(s *strings.Builder) {
	models := b.CollectBlocks(token.MODEL)
	if len(models) == 0 {
		return
	}
	s.WriteString("\n# --- Models ---\n")
	for _, block := range models {
		s.WriteString("\n")
		b.writeModel(s, block)
	}
}

// writeModel generates a Python model instantiation from a model block.
func (b *LangGraphBackend) writeModel(s *strings.Builder, block *ast.BlockStatement) {
	if block == nil {
		panic("BUG: writeModel called with nil block")
	}

	providerExpr, ok := block.GetFieldExpression("provider")
	if !ok {
		panic("BUG: writeModel called with block missing provider")
	}

	// Provider may be a folded expression (e.g. "open" + "ai"), not necessarily a string literal.
	providerValue, d := analyzer.ConstFold(providerExpr, b.Program)
	b.Program.Diagnostics = append(b.Program.Diagnostics, d...)
	if providerValue.Kind != analyzer.ConstString {
		// If this isn't a compile-time string, the analyzer should already have
		// reported a model-schema diagnostic; avoid duplicating errors here.
		return
	}

	info, known := providerRegistry[providerValue.Str]
	if !known {
		b.Program.Diagnostics = append(b.Program.Diagnostics, diagnostic.Diagnostic{
			Severity: diagnostic.Error,
			Code:     diagnostic.CodeUnknownProvider,
			Position: diagnostic.Position{Line: providerExpr.Start().Line, Column: providerExpr.Start().Column},
			Message:  fmt.Sprintf("unknown provider %q", providerValue.Str),
			Source:   "codegen",
		})
		return
	}

	// claude = ChatAnthropic(  # models.oc:12
	source := codegen.SourceComment(block.SourceFile, block.TokenStart.Line)
	fmt.Fprintf(s, "%s = %s(  # %s\n", block.Name, info.Class, source)

	field_names := []struct {
		orca_name      string
		langgraph_name string
	}{
		{
			orca_name:      "model_name",
			langgraph_name: "model",
		},
		{
			orca_name:      "temperature",
			langgraph_name: "temperature",
		},
	}

	for _, field_name := range field_names {
		expr, ok := block.GetFieldExpression(field_name.orca_name)
		if ok {
			fmt.Fprintf(s, "    %s=%s,\n", field_name.langgraph_name, python.OrcaToPythonExpression(expr))
		}
	}

	s.WriteString(")\n")
}

func (b *LangGraphBackend) writeGraphState(s *strings.Builder) {
	s.WriteString("\n# --- Graph State ---\n")
	s.WriteString("class GraphState(TypedDict):\n")
	s.WriteString("    pass # TODO: writeGraphState\n")
}

// writeAgents emits agent block stubs under "# --- Agents ---".
func (b *LangGraphBackend) writeAgents(s *strings.Builder) {
	agents := b.CollectBlocks(token.AGENT)
	if len(agents) == 0 {
		return
	}
	s.WriteString("\n# --- Agents ---\n")
	for _, block := range agents {
		s.WriteString("\n")
		b.writeAgent(s, block)
	}
}

// writeAgent generates a Python create_react_agent call from an agent block.
// Produces: name = create_react_agent(model, tools=[...], prompt="persona")  # source:line
func (b *LangGraphBackend) writeAgent(s *strings.Builder, block *ast.BlockStatement) {
	if block == nil {
		panic("BUG: writeAgent called with nil block")
	}

	source := codegen.SourceComment(block.SourceFile, block.TokenStart.Line)

	// Extract the model expression. A missing model field is a schema violation that
	// the analyzer should already have reported; reaching here without one is a bug.
	modelExpr, ok := block.GetFieldExpression("model")
	if !ok {
		panic("BUG: writeAgent called with block missing model")
	}
	// Convert to Python: named reference (identifier) or inline block expression.
	modelStr := b.modelExprToPython(modelExpr)

	// Build the create_react_agent call arguments.
	call := fmt.Sprintf("%s = create_react_agent(%s", block.Name, modelStr)

	// Include tools only when the list is non-empty.
	if toolsExpr, ok := block.GetFieldExpression("tools"); ok {
		if list, ok := toolsExpr.(*ast.ListLiteral); ok && len(list.Elements) > 0 {
			call += ", tools=" + python.OrcaToPythonExpression(toolsExpr)
		}
	}

	// Include the persona as the prompt argument.
	if personaExpr, ok := block.GetFieldExpression("persona"); ok {
		call += ", prompt=" + python.OrcaToPythonExpression(personaExpr)
	}

	call += ")"
	fmt.Fprintf(s, "%s  # %s\n", call, source)
}

// modelExprToPython converts a model expression to its Python string representation.
// Named references (e.g. `model = gpt4`) become a Python variable name.
// Inline model block expressions (e.g. `model = model { provider = "openai", ... }`)
// are instantiated inline as the appropriate LangChain class constructor call.
func (b *LangGraphBackend) modelExprToPython(expr ast.Expression) string {
	be, ok := expr.(*ast.BlockExpression)
	if !ok || be.Kind != token.BlockModel {
		// Named reference or any non-inline-model expression — use standard conversion.
		return python.OrcaToPythonExpression(expr)
	}
	return b.inlineModelToPython(be)
}

// inlineModelToPython generates a Python constructor call from an inline model
// block expression, e.g. ChatOpenAI(model="gpt-4o", temperature=0.7).
// Emits a diagnostic and returns "None" for unknown or non-constant providers.
func (b *LangGraphBackend) inlineModelToPython(be *ast.BlockExpression) string {
	providerExpr := blockExprField(be, "provider")
	if providerExpr == nil {
		return "None"
	}

	providerValue, d := analyzer.ConstFold(providerExpr, b.Program)
	b.Program.Diagnostics = append(b.Program.Diagnostics, d...)
	if providerValue.Kind != analyzer.ConstString {
		return "None"
	}

	info, known := providerRegistry[providerValue.Str]
	if !known {
		b.Program.Diagnostics = append(b.Program.Diagnostics, diagnostic.Diagnostic{
			Severity: diagnostic.Error,
			Code:     diagnostic.CodeUnknownProvider,
			Position: diagnostic.Position{Line: providerExpr.Start().Line, Column: providerExpr.Start().Column},
			Message:  fmt.Sprintf("unknown provider %q", providerValue.Str),
			Source:   "codegen",
		})
		return "None"
	}

	fieldNames := []struct{ orca, py string }{
		{"model_name", "model"},
		{"temperature", "temperature"},
	}
	var args []string
	for _, fn := range fieldNames {
		if e := blockExprField(be, fn.orca); e != nil {
			args = append(args, fmt.Sprintf("%s=%s", fn.py, python.OrcaToPythonExpression(e)))
		}
	}
	return fmt.Sprintf("%s(%s)", info.Class, strings.Join(args, ", "))
}

// blockExprField returns the expression for the named field in a BlockExpression,
// or nil if no such field is present.
func blockExprField(be *ast.BlockExpression, field string) ast.Expression {
	for _, a := range be.Assignments {
		if a != nil && a.Name == field {
			return a.Value
		}
	}
	return nil
}
