// Visual graph → `.orca` source generator.
//
// Walks the store's (nodes, edges) tuple and emits a textual Orca program
// that the Go compiler should be able to consume. Pure function — no I/O,
// no mutation — re-run on every graph change to keep the code tab in sync.
//
// Design notes
// ────────────
// 1. **Edge semantics.** Only two edge kinds survive in the studio: purple
//    flow edges (`agent-out`/`trigger-out` → `agent-in`) become lines
//    inside `workflow main { ... }`, and branch route edges
//    (`route-<routeId>` → `agent-in`) populate a branch's `route = { ... }`
//    map instead.
//
// 2. **Identifier sanitisation.** Node labels are user-facing and can be
//    anything. We lowercase, snake_case, strip leading digits, and dedupe
//    collisions with `_2`, `_3`. Reserved Orca keywords are avoided by
//    starting the dedupe counter at `_1`.
//
// 3. **Emission order.** Declarations must precede references, so we walk
//    `EMIT_ORDER` tuple list; non-agent kinds emit first, then agents
//    (which may reference knowledge/tools), then branch/triggers/schema.
//
// 4. **Field alignment.** Within every block the `=` signs line up on the
//    longest key. Matches the style in `compiler/codegen/testdata/golden/*.orca`.

import type { BlockNode, BlockEdge, BlockKind } from "./types";
import { BLOCK_DEFS, HANDLE_IDS } from "./block-defs";

// File header prepended to every generated `.orca` source. Tells the user
// where Orca lives and how to run the downloaded file. Kept intentionally
// short — it's the first thing anyone opening the file will see.
const FILE_HEADER = `// https://github.com/ThakeeNathees/orca
//
// Generated by Orca Studio.
// To run this workflow:
//   orca run
`;

// Keywords and a few literals that cannot be used as bare identifiers
// without the parser misinterpreting them as new blocks or constants.
const RESERVED = new Set<string>([
  "model",
  "agent",
  "tool",
  "knowledge",
  "memory",
  "workflow",
  "cron",
  "webhook",
  "chat",
  "schema",
  "input",
  "let",
  "branch",
  "true",
  "false",
  "null",
  "builtin",
]);

// Ordered BlockKind → Orca keyword mapping. Order is also the emission
// order (declarations must precede references): tools and knowledge emit
// first, then agents (which may reference them), then branch (whose route
// targets must already exist), then triggers and schema. Kinds not in
// this list (e.g. `input`, `workflow`) have no standalone block form.
const EMIT_ORDER: [BlockKind, string][] = [
  ["web_search", "tool"],
  ["code_exec", "tool"],
  ["api_request", "tool"],
  ["sql_query", "tool"],
  ["custom_tool", "tool"],
  ["knowledge", "knowledge"],
  ["agent", "agent"],
  ["branch", "branch"],
  ["cron", "cron"],
  ["webhook", "webhook"],
  ["chat", "chat"],
  ["schema", "schema"],
];

/** Turns a human-readable label into a snake_case Orca identifier. */
export function sanitizeIdent(label: string): string {
  let id = label.trim().toLowerCase().replace(/[^a-z0-9_]+/g, "_");
  id = id.replace(/_+/g, "_").replace(/^_+|_+$/g, "");
  if (id.length === 0) id = "unnamed";
  // Idents cannot start with a digit — prefix with underscore.
  if (/^[0-9]/.test(id)) id = "_" + id;
  return id;
}

/**
 * Assigns a unique identifier per node. Collisions and reserved-keyword
 * shadows are resolved by appending `_1`, `_2`, … to the sanitized base
 * until a free name is found. Returns a map of nodeId → ident.
 */
function assignIdents(nodes: BlockNode[]): Map<string, string> {
  const used = new Set<string>();
  const out = new Map<string, string>();

  for (const node of nodes) {
    const base = sanitizeIdent(node.data.label);
    // If the raw base clashes with a keyword or an already-used name, walk
    // the suffix counter starting at 1 until we find a free slot.
    let candidate = base;
    let n = 1;
    while (RESERVED.has(candidate) || used.has(candidate)) {
      candidate = `${base}_${n++}`;
    }
    used.add(candidate);
    out.set(node.id, candidate);
  }
  return out;
}

/** Escapes a string for emission inside double-quoted `.orca` literals. */
function escapeString(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

/** Renders a scalar field value in its `.orca` surface form. */
function formatValue(v: string | number): string {
  if (typeof v === "number") return String(v);
  return `"${escapeString(v)}"`;
}

interface FieldEntry {
  key: string;
  /** Already-rendered right-hand side: quoted string, number, ident, or list. */
  rendered: string;
}

/**
 * Emits a block with `=` signs aligned on the longest key. Empty blocks
 * collapse to a single line so golden diffs stay tidy.
 */
function emitBlock(
  keyword: string,
  name: string,
  fields: FieldEntry[]
): string {
  if (fields.length === 0) return `${keyword} ${name} {}`;
  const maxKey = Math.max(...fields.map((f) => f.key.length));
  const body = fields
    .map((f) => `  ${f.key.padEnd(maxKey)} = ${f.rendered}`)
    .join("\n");
  return `${keyword} ${name} {\n${body}\n}`;
}

/**
 * Emits the `@ui(x, y)` annotation that records a node's canvas position.
 * Positional args (not named) keep the output compatible with the current
 * annotation-expression parser. The x/y pair is rounded to integers since
 * the studio's snap grid already quantises to 10px — sub-pixel drift
 * would just produce noise in the generated source.
 */
function emitUiAnnotation(node: BlockNode): string {
  const x = Math.round(node.position.x);
  const y = Math.round(node.position.y);
  return `@ui(${x}, ${y})`;
}

/**
 * Is this field non-empty enough to emit? Empty strings are skipped (they
 * come from placeholder password/text inputs the user hasn't filled in),
 * but numeric 0 and boolean false are preserved as legitimate values.
 */
function shouldEmitField(v: string | number | undefined | null): boolean {
  if (v === undefined || v === null) return false;
  if (typeof v === "string" && v.length === 0) return false;
  return true;
}

/* ── Main entry point ────────────────────────────────────────────────── */

/**
 * Generates a complete `.orca` source string from a studio graph. The output
 * ends with a trailing newline (POSIX convention) except when the graph is
 * empty, in which case the empty string is returned.
 */
export function generateOrcaSource(
  nodes: BlockNode[],
  edges: BlockEdge[]
): string {
  if (nodes.length === 0) return "";

  const idents = assignIdents(nodes);
  const nodeById = new Map(nodes.map((n) => [n.id, n]));

  /* ---------- Edge resolution ---------- */
  // Flow edges that become lines inside `workflow main { ... }`.
  const flowEdges: { fromId: string; toId: string }[] = [];

  // Per-branch route wiring: branchNodeId → routeId → target idents. Filled
  // from edges whose source handle is `route-<routeId>`. Used when emitting
  // the branch block's `route = { ... }` map.
  const routesOfBranch = new Map<string, Map<string, string[]>>();

  for (const e of edges) {
    const src = nodeById.get(e.source);
    const tgt = nodeById.get(e.target);
    if (!src || !tgt) continue;
    const tgtIdent = idents.get(tgt.id)!;

    const sh = e.sourceHandle ?? "";
    const th = e.targetHandle ?? "";

    // Branch route edges are NOT workflow flow edges — they populate the
    // branch block's `route = { ... }` map instead. The target handle is
    // still `agent-in` (branch routes feed into agents) but the source is
    // a dynamic `route-<routeId>` handle owned by the branch node.
    if (src.data.kind === "branch" && sh.startsWith(HANDLE_IDS.routePrefix)) {
      const routeId = sh.slice(HANDLE_IDS.routePrefix.length);
      let branchMap = routesOfBranch.get(src.id);
      if (!branchMap) {
        branchMap = new Map();
        routesOfBranch.set(src.id, branchMap);
      }
      const list = branchMap.get(routeId) ?? [];
      if (!list.includes(tgtIdent)) list.push(tgtIdent);
      branchMap.set(routeId, list);
      continue;
    }

    // Every remaining edge is a purple agent-typed flow connection: either
    // a trigger feeding into the first node (`trigger-out` → `agent-in`) or
    // a node-to-node workflow step (`agent-out` → `agent-in`).
    const isTriggerFlow = sh === HANDLE_IDS.triggerOut && th === HANDLE_IDS.agentIn;
    const isAgentFlow = sh === HANDLE_IDS.agentOut && th === HANDLE_IDS.agentIn;
    if (isTriggerFlow || isAgentFlow) {
      flowEdges.push({ fromId: src.id, toId: tgt.id });
    }
  }

  /* ---------- Emit top-level blocks ---------- */
  const sections: string[] = [];

  for (const [kind, keyword] of EMIT_ORDER) {
    for (const node of nodes) {
      if (node.data.kind !== kind) continue;
      const name = idents.get(node.id)!;
      const fields: FieldEntry[] = [];

      if (kind === "agent") {
        // Model, memory, tools, and knowledge now live on the Agent entity
        // (Agents section) rather than as graph edges. The generated agent
        // block only carries its persona — the rest is referenced by name
        // at deploy time via the entity ID.
        const def = BLOCK_DEFS[kind];
        for (const fieldDef of def.fields) {
          const v = node.data.fields[fieldDef.key];
          if (!shouldEmitField(v)) continue;
          fields.push({
            key: fieldDef.key,
            rendered: formatValue(v as string | number),
          });
        }
      } else if (kind === "branch") {
        // Branch nodes carry a `transform` lambda (raw code, not a quoted
        // string) and a `route` map whose entries come from edges leaving
        // each per-route source handle. A route with no outgoing edge is
        // skipped so the generated `.orca` stays compiler-valid.
        const transformRaw = node.data.fields.transform;
        if (typeof transformRaw === "string" && transformRaw.length > 0) {
          fields.push({ key: "transform", rendered: transformRaw });
        }
        const branchRoutes = node.data.routes ?? [];
        const routeMap = routesOfBranch.get(node.id);
        const entries: string[] = [];
        for (const route of branchRoutes) {
          const targets = routeMap?.get(route.id) ?? [];
          if (targets.length === 0) continue;
          if (route.key.length === 0) continue;
          // Multi-target routes (one key fanning out) aren't expressible
          // in the current branch schema — emit the first target and rely
          // on user edits if they need more. TODO: support fan-out routes
          // once the compiler accepts lists here.
          entries.push(`"${escapeString(route.key)}": ${targets[0]}`);
        }
        if (entries.length > 0) {
          fields.push({
            key: "route",
            rendered: `{\n${entries
              .map((e) => `    ${e},`)
              .join("\n")}\n  }`,
          });
        }
      } else if (kind === "schema") {
        // The studio schema node's `name` field duplicates the block
        // identifier, so we intentionally emit an empty body — users can
        // add record fields in the code tab once that's editable.
      } else {
        // Generic path: iterate the BlockDef field order for deterministic
        // output regardless of how the node's field map was mutated.
        const def = BLOCK_DEFS[kind];
        for (const fieldDef of def.fields) {
          const v = node.data.fields[fieldDef.key];
          if (!shouldEmitField(v)) continue;
          fields.push({
            key: fieldDef.key,
            rendered: formatValue(v as string | number),
          });
        }
      }

      const block = emitBlock(keyword, name, fields);
      sections.push(`${emitUiAnnotation(node)}\n${block}`);
    }
  }

  /* ---------- Workflow synthesis ---------- */
  if (flowEdges.length > 0) {
    const lines = flowEdges
      .map(
        (e) => `  ${idents.get(e.fromId)!} -> ${idents.get(e.toId)!}`
      )
      .join("\n");
    sections.push(`workflow main {\n${lines}\n}`);
  }

  if (sections.length === 0) return "";
  return `${FILE_HEADER}\n${sections.join("\n\n")}\n`;
}
