# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

from langchain_openai import ChatOpenAI

from langchain_community.tools.web_search import WebSearchTool

from langchain_community.tools.calculator import CalculatorTool

# --- Models ---

gpt4 = orca.model(
    provider="openai",
    model_name="gpt-4o",
    temperature=0.5,
)

# --- Tools ---

web_search = orca.tool(
    invoke=WebSearchTool,
)

calculator = orca.tool(
    invoke=CalculatorTool,
)

# --- Graph State ---
class GraphState(TypedDict):
    __orca_trigger__: str | None
    __orca_payload__: dict | None

# --- Agents ---

researcher = orca.agent(
    model=gpt4,
    persona="You are a research assistant.",
    tools=[web_search, calculator],
)
