# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

from langchain_openai import ChatOpenAI

# --- Models ---

gpt4 = orca.model(
    provider="openai",
    model_name="gpt-4o",
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState

# --- Agents ---

writer = orca.agent(
    model=gpt4,
    persona="You are a helpful writer.",
)
