# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

# --- Inputs ---

apikey = orca.input(
    type=str,
    desc="the api key",
    default="sk-xxx",
    sensitive=True,
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState
