# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

# --- Inputs ---

apikey = orca.with_meta(
    orca.input(
        type=str,
    ),
    [
        orca.meta("desc", "User API key"),
        orca.meta("sensitive"),
    ],
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState
