# Auto-generated by Orca compiler — do not edit
from typing import TypedDict

"""Orca runtime — inlined into generated main.py.

These functions are called by generated code to create block instances.
All public names are prefixed with __orca_ to avoid collisions with user code.
"""

from __future__ import annotations

from types import SimpleNamespace
from typing import Any


def __orca_block(kind: str, **kwargs: Any) -> SimpleNamespace:
    """Create a block instance with the given kind and keyword fields."""
    return SimpleNamespace(_kind=kind, **kwargs)


def __orca_fields(params: dict[str, Any]) -> dict[str, Any]:
    """Filter out None values from a parameter dict to omit unset optional fields."""
    return {k: v for k, v in params.items() if v is not None}


def __orca_meta(name: str, *args: Any) -> SimpleNamespace:
    """Single Orca decorator as data (@name or @name(args...))."""
    return SimpleNamespace(_kind="meta", name=name, args=args)


def __orca_with_meta(value: Any, metas: list[Any]) -> SimpleNamespace:
    """Attach a non-empty list of __orca_meta() values to a block or field value."""
    return SimpleNamespace(_kind="with_meta", value=value, metas=metas)


def __orca_model(
    provider: str,
    model_name: str | SimpleNamespace,
    api_key: str | None = None,
    base_url: str | None = None,
    temperature: float | None = None,
) -> SimpleNamespace:
    return __orca_block("model", **__orca_fields(locals()))


def __orca_agent(
    model: str | SimpleNamespace,
    persona: str,
    tools: list[SimpleNamespace] | None = None,
    output_schema: SimpleNamespace | None = None,
) -> SimpleNamespace:
    return __orca_block("agent", **__orca_fields(locals()))


def __orca_tool(
    invoke: str | callable,
    desc: str | None = None,
    input_schema: SimpleNamespace | None = None,
    output_schema: SimpleNamespace | None = None,
) -> SimpleNamespace:
    return __orca_block("tool", **__orca_fields(locals()))


def __orca_knowledge(
    desc: str | None = None,
) -> SimpleNamespace:
    return __orca_block("knowledge", **__orca_fields(locals()))


def __orca_workflow(
    name: str | None = None,
    desc: str | None = None,
) -> SimpleNamespace:
    return __orca_block("workflow", **__orca_fields(locals()))


def __orca_cron(
    schedule: str,
    timezone: str | None = None,
) -> SimpleNamespace:
    return __orca_block("cron", **__orca_fields(locals()))


def __orca_webhook(
    path: str,
    method: str | None = None,
) -> SimpleNamespace:
    return __orca_block("webhook", **__orca_fields(locals()))


def __orca_input(
    type: SimpleNamespace,
    desc: str | None = None,
    default: Any | None = None,
    sensitive: bool | None = None,
) -> SimpleNamespace:
    return __orca_block("input", **__orca_fields(locals()))


def __orca_schema(**kwargs: Any) -> SimpleNamespace:
    return __orca_block("schema", **kwargs)


def __orca_let(**kwargs: Any) -> SimpleNamespace:
    return __orca_block("let", **kwargs)


def __orca_gather(state: dict, predecessors: list[str]) -> Any:
    """Collect predecessor outputs from workflow state.

    Single predecessor returns its value directly.
    Multiple predecessors returns a dict keyed by predecessor name.
    """
    raise NotImplementedError("TODO: __orca_gather")


def __orca_invoke_agent(agent: SimpleNamespace, input_data: Any) -> Any:
    """Invoke an agent node. Uses create_react_agent internally (works with or without tools)."""
    raise NotImplementedError("TODO: __orca_invoke_agent")


def __orca_invoke_tool(tool: SimpleNamespace, input_data: Any) -> Any:
    """Invoke a tool node directly."""
    raise NotImplementedError("TODO: __orca_invoke_tool")


# --- Inputs ---

apikey = __orca_with_meta(
    __orca_input(
        type=str,
    ),
    [
        __orca_meta("sensitive"),
    ],
)
