# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

# --- Knowledge ---

docs = orca.knowledge(
    desc="Company knowledge base",
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState
