# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

# --- Variables ---

vars = orca.let(
    name="orca",
    count=42,
    rate=3.14,
    enabled=False,
    nothing=None,
    items=["a", "b", "c"],
    config={"key": "value", "num": 1},
)

# --- Graph State ---
class GraphState(TypedDict):
    __orca_trigger__: str | None
    __orca_payload__: dict | None
