# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

# --- Variables ---

vars = orca.let(
    api_url="https://api.example.com",
    max_retries=3,
    temperature=0.7,
    debug=True,
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState
