# Auto-generated by Orca compiler — do not edit
from typing import TypedDict

# --- Variables ---

api_url = "https://api.example.com"  # line 2

max_retries = 3  # line 3

temperature = 0.7  # line 4

debug = True  # line 5

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState
