# Auto-generated by Orca compiler — do not edit
from typing import TypedDict

# --- Variables ---

name = "orca"  # line 2

count = 42  # line 3

rate = 3.14  # line 4

enabled = False  # line 5

nothing = None  # line 6

items = ["a", "b", "c"]  # line 7

config = {"key": "value", "num": 1}  # line 8

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState
