# Auto-generated by Orca compiler — do not edit

from langchain_openai import ChatOpenAI

# --- Variables ---

api_key = "sk-123"  # line 2

# --- Models ---

gpt4 = ChatOpenAI(model="gpt-4o", temperature=1.0)  # line 5
