# Auto-generated by Orca compiler — do not edit
"""Orca runtime — inlined into generated main.py.

These functions are called by generated code to create block instances.
All public names are prefixed with __orca_ to avoid collisions with user code.
"""

from __future__ import annotations

from langchain_openai import ChatOpenAI
import sys

from types import SimpleNamespace
from typing import Any, TypedDict

from langchain.agents import create_agent


def _orca__block(kind: str, **kwargs: Any) -> SimpleNamespace:
    """Create a block instance with the given kind and keyword fields."""
    return SimpleNamespace(_kind=kind, **kwargs)


def _orca__fields(params: dict[str, Any]) -> dict[str, Any]:
    """Filter out None values from a parameter dict to omit unset optional fields."""
    return {k: v for k, v in params.items() if v is not None}


def _orca__meta(name: str, *args: Any) -> SimpleNamespace:
    """Single Orca decorator as data (@name or @name(args...))."""
    return SimpleNamespace(_kind="meta", name=name, args=args)


def _orca__with_meta(value: Any, metas: list[Any]) -> SimpleNamespace:
    """Attach a non-empty list of _orca__meta() values to a block or field value."""
    return SimpleNamespace(_kind="with_meta", value=value, metas=metas)



def _orca__gather(state: dict, predecessors: list[str]) -> Any:
    """Collect predecessor outputs from workflow state.

    No predecessors (entry nodes) use the _orca__payload field as input.
    Single predecessor returns its value directly.
    Multiple predecessors returns a dict keyed by predecessor name.
    """
    if len(predecessors) == 0:
        return state.get("_orca__payload")
    if len(predecessors) == 1:
        return state.get(predecessors[0])
    return {k: state.get(k) for k in predecessors}


def _orca__resolve_model(model_ns: SimpleNamespace) -> Any:
    """Instantiate a LangChain ChatModel from a model SimpleNamespace.

    The provider_class field is the actual class (e.g. ChatOpenAI), resolved
    at compile time by the codegen. No runtime provider lookup needed.
    """
    return model_ns.provider_class(**_orca__fields({
        "model": model_ns.model_name,
        "temperature": getattr(model_ns, "temperature", None),
        "api_key": getattr(model_ns, "api_key", None),
        "base_url": getattr(model_ns, "base_url", None),
    }))


def _orca__invoke_agent(agent: SimpleNamespace, input_data: Any) -> Any:
    """Invoke an agent node using create_agent (works with or without tools)."""
    llm = _orca__resolve_model(agent.model)
    tools = [t.invoke for t in getattr(agent, "tools", None) or []]
    output_schema = getattr(agent, "output_schema", None)

    if output_schema is not None:
        llm = llm.with_structured_output(output_schema)

    react = create_agent(llm, tools)
    messages = [{"role": "system", "content": agent.persona}]
    # Use input_data as user message, or default to "Proceed" if empty.
    user_content = str(input_data).strip() if input_data else ""
    if not user_content:
        user_content = "Proceed with the instructions provided."
    messages.append({"role": "user", "content": user_content})

    result = react.invoke({"messages": messages})

    # Extract the final AI message content.
    last_msg = result["messages"][-1]
    if output_schema is not None:
        # Structured output is attached to the last tool message or parsed content.
        return getattr(last_msg, "content", last_msg)
    return last_msg.content


def _orca__invoke_tool(tool: SimpleNamespace, input_data: Any) -> Any:
    """Invoke a tool node by calling its invoke callable directly."""
    return tool.invoke(input_data)


vars = _orca__block("let", 
    api_key="sk-123",
)

gpt4 = _orca__block("model", 
    provider_class=ChatOpenAI,
    model_name="gpt-4o",
    temperature=1,
)
