# Auto-generated by Orca compiler — do not edit
from typing import TypedDict

from langchain_anthropic import ChatAnthropic

from langchain_google_genai import ChatGoogleGenerativeAI

from langchain_openai import ChatOpenAI

"""Orca runtime — inlined into generated main.py.

These functions are called by generated code to create block instances.
All public names are prefixed with __orca_ to avoid collisions with user code.
"""

from __future__ import annotations

from types import SimpleNamespace
from typing import Any


def __orca_block(kind: str, **kwargs: Any) -> SimpleNamespace:
    """Create a block instance with the given kind and keyword fields."""
    return SimpleNamespace(_kind=kind, **kwargs)


def __orca_fields(params: dict[str, Any]) -> dict[str, Any]:
    """Filter out None values from a parameter dict to omit unset optional fields."""
    return {k: v for k, v in params.items() if v is not None}


def __orca_meta(name: str, *args: Any) -> SimpleNamespace:
    """Single Orca decorator as data (@name or @name(args...))."""
    return SimpleNamespace(_kind="meta", name=name, args=args)


def __orca_with_meta(value: Any, metas: list[Any]) -> SimpleNamespace:
    """Attach a non-empty list of __orca_meta() values to a block or field value."""
    return SimpleNamespace(_kind="with_meta", value=value, metas=metas)


def __orca_model(
    provider: str,
    model_name: str | SimpleNamespace,
    api_key: str | None = None,
    base_url: str | None = None,
    temperature: float | None = None,
) -> SimpleNamespace:
    return __orca_block("model", **__orca_fields(locals()))


def __orca_agent(
    model: str | SimpleNamespace,
    persona: str,
    tools: list[SimpleNamespace] | None = None,
    output_schema: SimpleNamespace | None = None,
) -> SimpleNamespace:
    return __orca_block("agent", **__orca_fields(locals()))


def __orca_tool(
    invoke: str | callable,
    desc: str | None = None,
    input_schema: SimpleNamespace | None = None,
    output_schema: SimpleNamespace | None = None,
) -> SimpleNamespace:
    return __orca_block("tool", **__orca_fields(locals()))


def __orca_knowledge(
    desc: str | None = None,
) -> SimpleNamespace:
    return __orca_block("knowledge", **__orca_fields(locals()))


def __orca_workflow(
    name: str | None = None,
    desc: str | None = None,
) -> SimpleNamespace:
    return __orca_block("workflow", **__orca_fields(locals()))


def __orca_cron(
    schedule: str,
    timezone: str | None = None,
) -> SimpleNamespace:
    return __orca_block("cron", **__orca_fields(locals()))


def __orca_webhook(
    path: str,
    method: str | None = None,
) -> SimpleNamespace:
    return __orca_block("webhook", **__orca_fields(locals()))


def __orca_input(
    type: SimpleNamespace,
    desc: str | None = None,
    default: Any | None = None,
    sensitive: bool | None = None,
) -> SimpleNamespace:
    return __orca_block("input", **__orca_fields(locals()))


def __orca_schema(**kwargs: Any) -> SimpleNamespace:
    return __orca_block("schema", **kwargs)


def __orca_let(**kwargs: Any) -> SimpleNamespace:
    return __orca_block("let", **kwargs)


def __orca_gather(state: dict, predecessors: list[str]) -> Any:
    """Collect predecessor outputs from workflow state.

    Single predecessor returns its value directly.
    Multiple predecessors returns a dict keyed by predecessor name.
    """
    if len(predecessors) == 1:
        return state.get(predecessors[0])
    return {k: state.get(k) for k in predecessors}


def __orca_resolve_model(model_ns: SimpleNamespace) -> Any:
    """Resolve a model SimpleNamespace to a LangChain ChatModel instance.

    Maps provider string to the corresponding LangChain class and passes
    through model_name, temperature, api_key, and base_url.
    """
    provider = model_ns.provider
    model_name = model_ns.model_name
    kwargs: dict[str, Any] = {"model": model_name}
    if getattr(model_ns, "temperature", None) is not None:
        kwargs["temperature"] = model_ns.temperature
    if getattr(model_ns, "api_key", None) is not None:
        kwargs["api_key"] = model_ns.api_key
    if getattr(model_ns, "base_url", None) is not None:
        kwargs["base_url"] = model_ns.base_url

    providers = {
        "openai": "ChatOpenAI",
        "anthropic": "ChatAnthropic",
        "google": "ChatGoogleGenerativeAI",
    }
    class_name = providers.get(provider)
    if class_name is None:
        raise ValueError(f"unsupported model provider: {provider!r}")

    # The class is already imported by the generated code.
    cls = globals().get(class_name)
    if cls is None:
        raise RuntimeError(
            f"{class_name} not found — ensure the provider import is generated"
        )
    return cls(**kwargs)


def __orca_invoke_agent(agent: SimpleNamespace, input_data: Any) -> Any:
    """Invoke an agent node using create_react_agent (works with or without tools)."""
    llm = __orca_resolve_model(agent.model)
    tools = [t.invoke for t in getattr(agent, "tools", None) or []]
    output_schema = getattr(agent, "output_schema", None)

    if output_schema is not None:
        llm = llm.with_structured_output(output_schema)

    react = create_react_agent(llm, tools)
    result = react.invoke(
        {"messages": [{"role": "system", "content": agent.persona},
                      {"role": "user", "content": str(input_data)}]}
    )

    # Extract the final AI message content.
    last_msg = result["messages"][-1]
    if output_schema is not None:
        # Structured output is attached to the last tool message or parsed content.
        return getattr(last_msg, "content", last_msg)
    return last_msg.content


def __orca_invoke_tool(tool: SimpleNamespace, input_data: Any) -> Any:
    """Invoke a tool node by calling its invoke callable directly."""
    return tool.invoke(input_data)


# --- Models ---

gpt4 = __orca_model(
    provider="openai",
    model_name="gpt-4o",
    temperature=0.7,
)

claude = __orca_model(
    provider="anthropic",
    model_name="claude-sonnet-4-20250514",
    temperature=0,
)

gemini = __orca_model(
    provider="google",
    model_name="gemini-pro",
)
