# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

from langchain_anthropic import ChatAnthropic

# --- Models ---

claude = orca.model(
    provider="anthropic",
    model_name="claude-sonnet-4-20250514",
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState
