# Auto-generated by Orca compiler — do not edit
from typing import TypedDict
from langgraph.prebuilt import create_react_agent

from langchain_openai import ChatOpenAI

# --- Models ---

gpt4 = ChatOpenAI(  # line 1
    model="gpt-4o",
    temperature=0.7,
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState

# --- Agents ---

writer = create_react_agent(gpt4, prompt="You are a helpful writer.")  # line 7
