# Auto-generated by Orca compiler — do not edit

from langchain_anthropic import ChatAnthropic

from langchain_google_genai import ChatGoogleGenerativeAI

from langchain_openai import ChatOpenAI

# --- Models ---

gpt4 = ChatOpenAI(model="gpt-4o", temperature=0.7)  # line 1

claude = ChatAnthropic(model="claude-sonnet-4-20250514", temperature=0.0)  # line 7

gemini = ChatGoogleGenerativeAI(model="gemini-pro")  # line 13
