# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

from langchain_openai import ChatOpenAI

# --- Models ---

gpt4 = orca.model(
    provider=orca.with_meta(
        "openai",
        [
            orca.meta("desc", "LLM provider id"),
        ],
    ),
    model_name="gpt-4o",
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState
