# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

from langchain_anthropic import ChatAnthropic

from langchain_google_genai import ChatGoogleGenerativeAI

from langchain_openai import ChatOpenAI

# --- Models ---

gpt4 = orca.model(
    provider="openai",
    model_name="gpt-4o",
    temperature=0.7,
)

claude = orca.model(
    provider="anthropic",
    model_name="claude-sonnet-4-20250514",
    temperature=0,
)

gemini = orca.model(
    provider="google",
    model_name="gemini-pro",
)

# --- Graph State ---
class GraphState(TypedDict):
    __orca_trigger__: str | None
    __orca_payload__: dict | None
