# Auto-generated by Orca compiler — do not edit
from typing import TypedDict

from langchain_openai import ChatOpenAI

# --- Models ---

gpt4 = ChatOpenAI(  # line 1
    model="gpt-4o",
    temperature=0.7,
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState

# --- Agents ---

def writer(state: GraphState) -> GraphState:
    # TODO: writeAgent
    return state
