# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

from langchain_anthropic import ChatAnthropic

from langchain_openai import ChatOpenAI

# --- Models ---

gpt4 = orca.model(
    provider="openai",
    model_name="gpt-4o",
)

claude = orca.model(
    provider="anthropic",
    model_name="claude-sonnet-4-20250514",
    temperature=0.3,
)

# --- Graph State ---
class GraphState(TypedDict):
    __orca_trigger__: str | None
    __orca_payload__: dict | None

# --- Agents ---

researcher = orca.agent(
    model=gpt4,
    persona="You find and summarize information.",
)

writer = orca.agent(
    model=claude,
    persona="You write polished articles from research notes.",
)
