# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

# --- Schemas ---

cfg = orca.schema(
    region=orca.with_meta(
        str,
        [
            orca.meta("required"),
            orca.meta("desc", "Region code"),
        ],
    ),
)

# --- Graph State ---
class GraphState(TypedDict):
    __orca_trigger__: str | None
    __orca_payload__: dict | None
