# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

# --- Schemas ---

vpc_data_t = orca.schema(
    region=str,
    instance_count=int,
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState
