# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

# --- Schemas ---

vpc_data_t = orca.schema(
    region=orca.with_meta(
        str,
        [
            orca.meta("desc", "AWS region"),
        ],
    ),
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState
