# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

# --- Schemas ---

vpc_data_t = orca.schema(
    region=str,
)

# --- Inputs ---

vpc_data = orca.input(
    type=vpc_data_t,
    desc="VPC configuration",
)

# --- Graph State ---
class GraphState(TypedDict):
    __orca_trigger__: str | None
    __orca_payload__: dict | None
