# Auto-generated by Orca compiler — do not edit
from typing import TypedDict

from langchain_openai import ChatOpenAI

from langgraph.graph import StateGraph, START, END

"""Orca runtime — inlined into generated main.py.

These functions are called by generated code to create block instances.
All public names are prefixed with __orca_ to avoid collisions with user code.
"""

from __future__ import annotations

from types import SimpleNamespace
from typing import Any


def __orca_block(kind: str, **kwargs: Any) -> SimpleNamespace:
    """Create a block instance with the given kind and keyword fields."""
    return SimpleNamespace(_kind=kind, **kwargs)


def __orca_fields(params: dict[str, Any]) -> dict[str, Any]:
    """Filter out None values from a parameter dict to omit unset optional fields."""
    return {k: v for k, v in params.items() if v is not None}


def __orca_meta(name: str, *args: Any) -> SimpleNamespace:
    """Single Orca decorator as data (@name or @name(args...))."""
    return SimpleNamespace(_kind="meta", name=name, args=args)


def __orca_with_meta(value: Any, metas: list[Any]) -> SimpleNamespace:
    """Attach a non-empty list of __orca_meta() values to a block or field value."""
    return SimpleNamespace(_kind="with_meta", value=value, metas=metas)


def __orca_model(
    provider: str,
    model_name: str | SimpleNamespace,
    api_key: str | None = None,
    base_url: str | None = None,
    temperature: float | None = None,
) -> SimpleNamespace:
    return __orca_block("model", **__orca_fields(locals()))


def __orca_agent(
    model: str | SimpleNamespace,
    persona: str,
    tools: list[SimpleNamespace] | None = None,
    output_schema: SimpleNamespace | None = None,
) -> SimpleNamespace:
    return __orca_block("agent", **__orca_fields(locals()))


def __orca_tool(
    invoke: str | callable,
    desc: str | None = None,
    input_schema: SimpleNamespace | None = None,
    output_schema: SimpleNamespace | None = None,
) -> SimpleNamespace:
    return __orca_block("tool", **__orca_fields(locals()))


def __orca_knowledge(
    desc: str | None = None,
) -> SimpleNamespace:
    return __orca_block("knowledge", **__orca_fields(locals()))


def __orca_workflow(
    name: str | None = None,
    desc: str | None = None,
) -> SimpleNamespace:
    return __orca_block("workflow", **__orca_fields(locals()))


def __orca_cron(
    schedule: str,
    timezone: str | None = None,
) -> SimpleNamespace:
    return __orca_block("cron", **__orca_fields(locals()))


def __orca_webhook(
    path: str,
    method: str | None = None,
) -> SimpleNamespace:
    return __orca_block("webhook", **__orca_fields(locals()))


def __orca_input(
    type: SimpleNamespace,
    desc: str | None = None,
    default: Any | None = None,
    sensitive: bool | None = None,
) -> SimpleNamespace:
    return __orca_block("input", **__orca_fields(locals()))


def __orca_schema(**kwargs: Any) -> SimpleNamespace:
    return __orca_block("schema", **kwargs)


def __orca_let(**kwargs: Any) -> SimpleNamespace:
    return __orca_block("let", **kwargs)


# --- Models ---

gpt4 = __orca_model(
    provider="openai",
    model_name="gpt-4o",
)

# --- Agents ---

classifier = __orca_agent(
    model=gpt4,
    persona="You classify incoming requests.",
)

writer = __orca_agent(
    model=gpt4,
    persona="You write content.",
)

analyst = __orca_agent(
    model=gpt4,
    persona="You analyze data.",
)

reviewer = __orca_agent(
    model=gpt4,
    persona="You review and merge results.",
)

# --- Workflows ---

class __orca_state_diamond(TypedDict):
    __orca_trigger: str | None
    __orca_payload: dict | None
    classifier: Any
    writer: Any
    analyst: Any
    reviewer: Any

def __orca_node_classifier(state: __orca_state_diamond) -> dict:
    """Workflow node wrapping 'classifier'."""
    pass  # TODO: implement node invocation for 'classifier'

def __orca_node_writer(state: __orca_state_diamond) -> dict:
    """Workflow node wrapping 'writer'."""
    pass  # TODO: implement node invocation for 'writer'

def __orca_node_analyst(state: __orca_state_diamond) -> dict:
    """Workflow node wrapping 'analyst'."""
    pass  # TODO: implement node invocation for 'analyst'

def __orca_node_reviewer(state: __orca_state_diamond) -> dict:
    """Workflow node wrapping 'reviewer'."""
    pass  # TODO: implement node invocation for 'reviewer'

def __orca_route_diamond(state: __orca_state_diamond) -> str:
    """Route to entry node based on trigger source."""
    return "classifier"

diamond = StateGraph(__orca_state_diamond)
diamond.add_node("classifier", __orca_node_classifier)
diamond.add_node("writer", __orca_node_writer)
diamond.add_node("analyst", __orca_node_analyst)
diamond.add_node("reviewer", __orca_node_reviewer)
diamond.add_conditional_edges(START, __orca_route_diamond)
diamond.add_edge("classifier", "writer")
diamond.add_edge("classifier", "analyst")
diamond.add_edge("writer", "reviewer")
diamond.add_edge("analyst", "reviewer")
diamond.add_edge("reviewer", END)
diamond = diamond.compile()
