# Auto-generated by Orca compiler — do not edit
"""Orca runtime — inlined into generated main.py.

These functions are called by generated code to create block instances.
All public names are prefixed with __orca_ to avoid collisions with user code.
"""

from __future__ import annotations

from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
import sys
from pydantic import BaseModel, Field

from types import SimpleNamespace
from typing import Any, TypedDict

from langchain.agents import create_agent


def __orca_block(kind: str, **kwargs: Any) -> SimpleNamespace:
    """Create a block instance with the given kind and keyword fields."""
    return SimpleNamespace(_kind=kind, **kwargs)


def __orca_fields(params: dict[str, Any]) -> dict[str, Any]:
    """Filter out None values from a parameter dict to omit unset optional fields."""
    return {k: v for k, v in params.items() if v is not None}


def __orca_meta(name: str, *args: Any) -> SimpleNamespace:
    """Single Orca decorator as data (@name or @name(args...))."""
    return SimpleNamespace(_kind="meta", name=name, args=args)


def __orca_with_meta(value: Any, metas: list[Any]) -> SimpleNamespace:
    """Attach a non-empty list of __orca_meta() values to a block or field value."""
    return SimpleNamespace(_kind="with_meta", value=value, metas=metas)


def __orca_model(
    provider_class: type,
    model_name: str | SimpleNamespace,
    api_key: str | None = None,
    base_url: str | None = None,
    temperature: float | None = None,
) -> SimpleNamespace:
    return __orca_block("model", **__orca_fields(locals()))


def __orca_agent(
    model: str | SimpleNamespace,
    persona: str,
    tools: list[SimpleNamespace] | None = None,
    output_schema: SimpleNamespace | None = None,
) -> SimpleNamespace:
    return __orca_block("agent", **__orca_fields(locals()))


def __orca_tool(
    invoke: str | callable,
    desc: str | None = None,
    input_schema: SimpleNamespace | None = None,
    output_schema: SimpleNamespace | None = None,
) -> SimpleNamespace:
    return __orca_block("tool", **__orca_fields(locals()))


def __orca_knowledge(
    desc: str | None = None,
) -> SimpleNamespace:
    return __orca_block("knowledge", **__orca_fields(locals()))


def __orca_workflow(
    name: str | None = None,
    desc: str | None = None,
) -> SimpleNamespace:
    return __orca_block("workflow", **__orca_fields(locals()))


def __orca_cron(
    schedule: str,
    timezone: str | None = None,
) -> SimpleNamespace:
    return __orca_block("cron", **__orca_fields(locals()))


def __orca_webhook(
    path: str,
    method: str | None = None,
) -> SimpleNamespace:
    return __orca_block("webhook", **__orca_fields(locals()))


def __orca_input(
    type: SimpleNamespace,
    desc: str | None = None,
    default: Any | None = None,
    sensitive: bool | None = None,
) -> SimpleNamespace:
    return __orca_block("input", **__orca_fields(locals()))


def __orca_schema(**kwargs: Any) -> SimpleNamespace:
    return __orca_block("schema", **kwargs)


def __orca_let(**kwargs: Any) -> SimpleNamespace:
    return __orca_block("let", **kwargs)


def __orca_gather(state: dict, predecessors: list[str]) -> Any:
    """Collect predecessor outputs from workflow state.

    No predecessors (entry nodes) use the __orca_payload field as input.
    Single predecessor returns its value directly.
    Multiple predecessors returns a dict keyed by predecessor name.
    """
    if len(predecessors) == 0:
        return state.get("__orca_payload")
    if len(predecessors) == 1:
        return state.get(predecessors[0])
    return {k: state.get(k) for k in predecessors}


def __orca_resolve_model(model_ns: SimpleNamespace) -> Any:
    """Instantiate a LangChain ChatModel from a model SimpleNamespace.

    The provider_class field is the actual class (e.g. ChatOpenAI), resolved
    at compile time by the codegen. No runtime provider lookup needed.
    """
    return model_ns.provider_class(**__orca_fields({
        "model": model_ns.model_name,
        "temperature": getattr(model_ns, "temperature", None),
        "api_key": getattr(model_ns, "api_key", None),
        "base_url": getattr(model_ns, "base_url", None),
    }))


def __orca_invoke_agent(agent: SimpleNamespace, input_data: Any) -> Any:
    """Invoke an agent node using create_agent (works with or without tools)."""
    llm = __orca_resolve_model(agent.model)
    tools = [t.invoke for t in getattr(agent, "tools", None) or []]
    output_schema = getattr(agent, "output_schema", None)

    if output_schema is not None:
        llm = llm.with_structured_output(output_schema)

    react = create_agent(llm, tools)
    result = react.invoke(
        {"messages": [{"role": "system", "content": agent.persona},
                      {"role": "user", "content": str(input_data)}]}
    )

    # Extract the final AI message content.
    last_msg = result["messages"][-1]
    if output_schema is not None:
        # Structured output is attached to the last tool message or parsed content.
        return getattr(last_msg, "content", last_msg)
    return last_msg.content


def __orca_invoke_tool(tool: SimpleNamespace, input_data: Any) -> Any:
    """Invoke a tool node by calling its invoke callable directly."""
    return tool.invoke(input_data)



class report(BaseModel):
    content: str

gpt4 = __orca_model(
    provider_class=ChatOpenAI,
    model_name="gpt-4o",
)

researcher = __orca_agent(
    model=gpt4,
    persona="Research.",
)

writer = __orca_agent(
    model=gpt4,
    persona="Write.",
    output_schema=report,
)

def validate__invoke_verbatim(report: str) -> str:
    return report

validate = __orca_tool(
    invoke=validate__invoke_verbatim,
)

class __orca_state_pipeline(TypedDict):
    __orca_trigger: str | None
    __orca_payload: dict | None
    researcher: Any
    writer: report | None
    validate: Any

def __orca_node_researcher(state: __orca_state_pipeline) -> dict:
    """Workflow node wrapping 'researcher'."""
    _predecessors = []
    _input = __orca_gather(state, _predecessors)
    _out = __orca_invoke_agent(researcher, _input)
    return {"researcher": _out}

def __orca_node_writer(state: __orca_state_pipeline) -> dict:
    """Workflow node wrapping 'writer'."""
    _predecessors = ["researcher"]
    _input = __orca_gather(state, _predecessors)
    _out = __orca_invoke_agent(writer, _input)
    return {"writer": _out}

def __orca_node_validate(state: __orca_state_pipeline) -> dict:
    """Workflow node wrapping 'validate'."""
    _predecessors = ["writer"]
    _input = __orca_gather(state, _predecessors)
    _out = __orca_invoke_tool(validate, _input)
    return {"validate": _out}

def __orca_route_pipeline(state: __orca_state_pipeline) -> str:
    """Route to entry node based on trigger source."""
    return "researcher"

pipeline = StateGraph(__orca_state_pipeline)
pipeline.add_node("researcher", __orca_node_researcher)
pipeline.add_node("writer", __orca_node_writer)
pipeline.add_node("validate", __orca_node_validate)
pipeline.add_conditional_edges(START, __orca_route_pipeline)
pipeline.add_edge("researcher", "writer")
pipeline.add_edge("writer", "validate")
pipeline.add_edge("validate", END)
pipeline = pipeline.compile()

if __name__ == "__main__":
    payload = sys.argv[1] if len(sys.argv) >= 2 else ""
    initial_state: __orca_state_pipeline = {
        "__orca_trigger": "",
        "__orca_payload": payload,
        "researcher": "",
        "writer": "",
        "validate": "",
    }
    final_state = pipeline.invoke(initial_state)
    print(final_state)
