# Auto-generated by Orca compiler — do not edit
"""Orca runtime — inlined into generated main.py.

These functions are called by generated code to create block instances.
All public names are prefixed with __orca_ to avoid collisions with user code.
"""

from __future__ import annotations

from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
import sys
from pydantic import BaseModel, Field

from types import SimpleNamespace
from typing import Any, TypedDict

from langchain.agents import create_agent


def _orca__block(kind: str, **kwargs: Any) -> SimpleNamespace:
    """Create a block instance with the given kind and keyword fields."""
    return SimpleNamespace(_kind=kind, **kwargs)


def _orca__fields(params: dict[str, Any]) -> dict[str, Any]:
    """Filter out None values from a parameter dict to omit unset optional fields."""
    return {k: v for k, v in params.items() if v is not None}


def _orca__meta(name: str, *args: Any) -> SimpleNamespace:
    """Single Orca decorator as data (@name or @name(args...))."""
    return SimpleNamespace(_kind="meta", name=name, args=args)


def _orca__with_meta(value: Any, metas: list[Any]) -> SimpleNamespace:
    """Attach a non-empty list of _orca__meta() values to a block or field value."""
    return SimpleNamespace(_kind="with_meta", value=value, metas=metas)



def _orca__gather(state: dict, predecessors: list[str]) -> Any:
    """Collect predecessor outputs from workflow state.

    No predecessors (entry nodes) use the _orca__payload field as input.
    Single predecessor returns its value directly.
    Multiple predecessors returns a dict keyed by predecessor name.
    """
    if len(predecessors) == 0:
        return state.get("_orca__payload")
    if len(predecessors) == 1:
        return state.get(predecessors[0])
    return {k: state.get(k) for k in predecessors}


def _orca__resolve_model(model_ns: SimpleNamespace) -> Any:
    """Instantiate a LangChain ChatModel from a model SimpleNamespace.

    The provider_class field is the actual class (e.g. ChatOpenAI), resolved
    at compile time by the codegen. No runtime provider lookup needed.
    """
    return model_ns.provider_class(**_orca__fields({
        "model": model_ns.model_name,
        "temperature": getattr(model_ns, "temperature", None),
        "api_key": getattr(model_ns, "api_key", None),
        "base_url": getattr(model_ns, "base_url", None),
    }))


def _orca__invoke_agent(agent: SimpleNamespace, input_data: Any) -> Any:
    """Invoke an agent node using create_agent (works with or without tools)."""
    llm = _orca__resolve_model(agent.model)
    tools = [t.invoke for t in getattr(agent, "tools", None) or []]
    output_schema = getattr(agent, "output_schema", None)

    if output_schema is not None:
        llm = llm.with_structured_output(output_schema)

    react = create_agent(llm, tools)
    messages = [{"role": "system", "content": agent.persona}]
    # Use input_data as user message, or default to "Proceed" if empty.
    user_content = str(input_data).strip() if input_data else ""
    if not user_content:
        user_content = "Proceed with the instructions provided."
    messages.append({"role": "user", "content": user_content})

    result = react.invoke({"messages": messages})

    # Extract the final AI message content.
    last_msg = result["messages"][-1]
    if output_schema is not None:
        # Structured output is attached to the last tool message or parsed content.
        return getattr(last_msg, "content", last_msg)
    return last_msg.content


def _orca__invoke_tool(tool: SimpleNamespace, input_data: Any) -> Any:
    """Invoke a tool node by calling its invoke callable directly."""
    return tool.invoke(input_data)



class report(BaseModel):
    content: str = Field(description="The report content")
    score: int = Field(description="Quality score")

gpt4 = _orca__block("model", 
    provider_class=ChatOpenAI,
    model_name="gpt-4o",
)

researcher = _orca__block("agent", 
    model=gpt4,
    persona="Research topics.",
)

writer = _orca__block("agent", 
    model=gpt4,
    persona="Write reports.",
    output_schema=report,
)

class _orca__state_pipeline(TypedDict):
    _orca__trigger: str | None
    _orca__payload: dict | None
    researcher: Any
    writer: report | None

def _orca__node_researcher(state: _orca__state_pipeline) -> dict:
    """Workflow node wrapping 'researcher'."""
    _predecessors = []
    _input = _orca__gather(state, _predecessors)
    _out = _orca__invoke_agent(researcher, _input)
    return {"researcher": _out}

def _orca__node_writer(state: _orca__state_pipeline) -> dict:
    """Workflow node wrapping 'writer'."""
    _predecessors = ["researcher"]
    _input = _orca__gather(state, _predecessors)
    _out = _orca__invoke_agent(writer, _input)
    return {"writer": _out}

def _orca__route_pipeline(state: _orca__state_pipeline) -> str:
    """Route to entry node based on trigger source."""
    return "researcher"

pipeline = StateGraph(_orca__state_pipeline)
pipeline.add_node("researcher", _orca__node_researcher)
pipeline.add_node("writer", _orca__node_writer)
pipeline.add_conditional_edges(START, _orca__route_pipeline)
pipeline.add_edge("researcher", "writer")
pipeline.add_edge("writer", END)
pipeline = pipeline.compile()

if __name__ == "__main__":
    payload = sys.argv[1] if len(sys.argv) >= 2 else ""
    initial_state: _orca__state_pipeline = {
        "_orca__trigger": "",
        "_orca__payload": payload,
        "researcher": "",
        "writer": "",
    }
    final_state = pipeline.invoke(initial_state)
    print(final_state)
