# Auto-generated by Orca compiler — do not edit
"""Orca runtime — inlined into generated main.py.

These functions are called by generated code to create block instances.
All public names are prefixed with __orca_ to avoid collisions with user code.
"""

from __future__ import annotations

from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
from langchain.agents import create_agent

from types import SimpleNamespace, TypedDict
from typing import Any


def __orca_block(kind: str, **kwargs: Any) -> SimpleNamespace:
    """Create a block instance with the given kind and keyword fields."""
    return SimpleNamespace(_kind=kind, **kwargs)


def __orca_fields(params: dict[str, Any]) -> dict[str, Any]:
    """Filter out None values from a parameter dict to omit unset optional fields."""
    return {k: v for k, v in params.items() if v is not None}


def __orca_meta(name: str, *args: Any) -> SimpleNamespace:
    """Single Orca decorator as data (@name or @name(args...))."""
    return SimpleNamespace(_kind="meta", name=name, args=args)


def __orca_with_meta(value: Any, metas: list[Any]) -> SimpleNamespace:
    """Attach a non-empty list of __orca_meta() values to a block or field value."""
    return SimpleNamespace(_kind="with_meta", value=value, metas=metas)


def __orca_model(
    provider_class: type,
    model_name: str | SimpleNamespace,
    api_key: str | None = None,
    base_url: str | None = None,
    temperature: float | None = None,
) -> SimpleNamespace:
    return __orca_block("model", **__orca_fields(locals()))


def __orca_agent(
    model: str | SimpleNamespace,
    persona: str,
    tools: list[SimpleNamespace] | None = None,
    output_schema: SimpleNamespace | None = None,
) -> SimpleNamespace:
    return __orca_block("agent", **__orca_fields(locals()))


def __orca_tool(
    invoke: str | callable,
    desc: str | None = None,
    input_schema: SimpleNamespace | None = None,
    output_schema: SimpleNamespace | None = None,
) -> SimpleNamespace:
    return __orca_block("tool", **__orca_fields(locals()))


def __orca_knowledge(
    desc: str | None = None,
) -> SimpleNamespace:
    return __orca_block("knowledge", **__orca_fields(locals()))


def __orca_workflow(
    name: str | None = None,
    desc: str | None = None,
) -> SimpleNamespace:
    return __orca_block("workflow", **__orca_fields(locals()))


def __orca_cron(
    schedule: str,
    timezone: str | None = None,
) -> SimpleNamespace:
    return __orca_block("cron", **__orca_fields(locals()))


def __orca_webhook(
    path: str,
    method: str | None = None,
) -> SimpleNamespace:
    return __orca_block("webhook", **__orca_fields(locals()))


def __orca_input(
    type: SimpleNamespace,
    desc: str | None = None,
    default: Any | None = None,
    sensitive: bool | None = None,
) -> SimpleNamespace:
    return __orca_block("input", **__orca_fields(locals()))


def __orca_schema(**kwargs: Any) -> SimpleNamespace:
    return __orca_block("schema", **kwargs)


def __orca_let(**kwargs: Any) -> SimpleNamespace:
    return __orca_block("let", **kwargs)


def __orca_gather(state: dict, predecessors: list[str]) -> Any:
    """Collect predecessor outputs from workflow state.

    Single predecessor returns its value directly.
    Multiple predecessors returns a dict keyed by predecessor name.
    """
    if len(predecessors) == 1:
        return state.get(predecessors[0])
    return {k: state.get(k) for k in predecessors}


def __orca_resolve_model(model_ns: SimpleNamespace) -> Any:
    """Instantiate a LangChain ChatModel from a model SimpleNamespace.

    The provider_class field is the actual class (e.g. ChatOpenAI), resolved
    at compile time by the codegen. No runtime provider lookup needed.
    """
    return model_ns.provider_class(**__orca_fields({
        "model": model_ns.model_name,
        "temperature": getattr(model_ns, "temperature", None),
        "api_key": getattr(model_ns, "api_key", None),
        "base_url": getattr(model_ns, "base_url", None),
    }))


def __orca_invoke_agent(agent: SimpleNamespace, input_data: Any) -> Any:
    """Invoke an agent node using create_agent (works with or without tools)."""
    llm = __orca_resolve_model(agent.model)
    tools = [t.invoke for t in getattr(agent, "tools", None) or []]
    output_schema = getattr(agent, "output_schema", None)

    if output_schema is not None:
        llm = llm.with_structured_output(output_schema)

    react = create_agent(llm, tools)
    result = react.invoke(
        {"messages": [{"role": "system", "content": agent.persona},
                      {"role": "user", "content": str(input_data)}]}
    )

    # Extract the final AI message content.
    last_msg = result["messages"][-1]
    if output_schema is not None:
        # Structured output is attached to the last tool message or parsed content.
        return getattr(last_msg, "content", last_msg)
    return last_msg.content


def __orca_invoke_tool(tool: SimpleNamespace, input_data: Any) -> Any:
    """Invoke a tool node by calling its invoke callable directly."""
    return tool.invoke(input_data)


# --- Models ---

gpt4 = __orca_model(
    provider_class=ChatOpenAI,
    model_name="gpt-4o",
)

# --- Agents ---

classifier = __orca_agent(
    model=gpt4,
    persona="You classify incoming requests.",
)

writer = __orca_agent(
    model=gpt4,
    persona="You write content.",
)

analyst = __orca_agent(
    model=gpt4,
    persona="You analyze data.",
)

reviewer = __orca_agent(
    model=gpt4,
    persona="You review and merge results.",
)

# --- Workflows ---

class __orca_state_diamond(TypedDict):
    __orca_trigger: str | None
    __orca_payload: dict | None
    classifier: Any
    writer: Any
    analyst: Any
    reviewer: Any

def __orca_node_classifier(state: __orca_state_diamond) -> dict:
    """Workflow node wrapping 'classifier'."""
    input_data = state["__orca_payload"]
    result = __orca_invoke_agent(classifier, input_data)
    return {"classifier": result}

def __orca_node_writer(state: __orca_state_diamond) -> dict:
    """Workflow node wrapping 'writer'."""
    input_data = __orca_gather(state, ["classifier"])
    result = __orca_invoke_agent(writer, input_data)
    return {"writer": result}

def __orca_node_analyst(state: __orca_state_diamond) -> dict:
    """Workflow node wrapping 'analyst'."""
    input_data = __orca_gather(state, ["classifier"])
    result = __orca_invoke_agent(analyst, input_data)
    return {"analyst": result}

def __orca_node_reviewer(state: __orca_state_diamond) -> dict:
    """Workflow node wrapping 'reviewer'."""
    input_data = __orca_gather(state, ["writer", "analyst"])
    result = __orca_invoke_agent(reviewer, input_data)
    return {"reviewer": result}

def __orca_route_diamond(state: __orca_state_diamond) -> str:
    """Route to entry node based on trigger source."""
    return "classifier"

diamond = StateGraph(__orca_state_diamond)
diamond.add_node("classifier", __orca_node_classifier)
diamond.add_node("writer", __orca_node_writer)
diamond.add_node("analyst", __orca_node_analyst)
diamond.add_node("reviewer", __orca_node_reviewer)
diamond.add_conditional_edges(START, __orca_route_diamond)
diamond.add_edge("classifier", "writer")
diamond.add_edge("classifier", "analyst")
diamond.add_edge("writer", "reviewer")
diamond.add_edge("analyst", "reviewer")
diamond.add_edge("reviewer", END)
diamond = diamond.compile()
