# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

from langchain_openai import ChatOpenAI

from langgraph.graph import StateGraph, START, END

# --- Models ---

gpt4 = orca.model(
    provider="openai",
    model_name="gpt-4o",
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState

# --- Agents ---

researcher = orca.agent(
    model=gpt4,
    persona="You research topics.",
)

writer = orca.agent(
    model=gpt4,
    persona="You write articles.",
)

reviewer = orca.agent(
    model=gpt4,
    persona="You review articles.",
)

# --- Workflows ---

def _node_researcher(state: GraphState) -> dict:
    """Workflow node wrapping 'researcher'."""
    pass  # TODO: implement node invocation for 'researcher'

def _node_writer(state: GraphState) -> dict:
    """Workflow node wrapping 'writer'."""
    pass  # TODO: implement node invocation for 'writer'

def _node_reviewer(state: GraphState) -> dict:
    """Workflow node wrapping 'reviewer'."""
    pass  # TODO: implement node invocation for 'reviewer'

pipeline = StateGraph(GraphState)
pipeline.add_node("researcher", _node_researcher)
pipeline.add_node("writer", _node_writer)
pipeline.add_node("reviewer", _node_reviewer)
pipeline.add_edge(START, "researcher")
pipeline.add_edge("researcher", "writer")
pipeline.add_edge("writer", "reviewer")
pipeline.add_edge("reviewer", END)
pipeline = pipeline.compile()
