# Auto-generated by Orca compiler — do not edit
"""Orca runtime — inlined into generated main.py.

These functions are called by generated code to create block instances.
All public names are prefixed with __orca_ to avoid collisions with user code.
"""

from __future__ import annotations

from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
import sys

from types import SimpleNamespace
from typing import Any, TypedDict

from langchain.agents import create_agent


def __orca_block(kind: str, **kwargs: Any) -> SimpleNamespace:
    """Create a block instance with the given kind and keyword fields."""
    return SimpleNamespace(_kind=kind, **kwargs)


def __orca_fields(params: dict[str, Any]) -> dict[str, Any]:
    """Filter out None values from a parameter dict to omit unset optional fields."""
    return {k: v for k, v in params.items() if v is not None}


def __orca_meta(name: str, *args: Any) -> SimpleNamespace:
    """Single Orca decorator as data (@name or @name(args...))."""
    return SimpleNamespace(_kind="meta", name=name, args=args)


def __orca_with_meta(value: Any, metas: list[Any]) -> SimpleNamespace:
    """Attach a non-empty list of __orca_meta() values to a block or field value."""
    return SimpleNamespace(_kind="with_meta", value=value, metas=metas)



def __orca_gather(state: dict, predecessors: list[str]) -> Any:
    """Collect predecessor outputs from workflow state.

    No predecessors (entry nodes) use the __orca_payload field as input.
    Single predecessor returns its value directly.
    Multiple predecessors returns a dict keyed by predecessor name.
    """
    if len(predecessors) == 0:
        return state.get("__orca_payload")
    if len(predecessors) == 1:
        return state.get(predecessors[0])
    return {k: state.get(k) for k in predecessors}


def __orca_resolve_model(model_ns: SimpleNamespace) -> Any:
    """Instantiate a LangChain ChatModel from a model SimpleNamespace.

    The provider_class field is the actual class (e.g. ChatOpenAI), resolved
    at compile time by the codegen. No runtime provider lookup needed.
    """
    return model_ns.provider_class(**__orca_fields({
        "model": model_ns.model_name,
        "temperature": getattr(model_ns, "temperature", None),
        "api_key": getattr(model_ns, "api_key", None),
        "base_url": getattr(model_ns, "base_url", None),
    }))


def __orca_invoke_agent(agent: SimpleNamespace, input_data: Any) -> Any:
    """Invoke an agent node using create_agent (works with or without tools)."""
    llm = __orca_resolve_model(agent.model)
    tools = [t.invoke for t in getattr(agent, "tools", None) or []]
    output_schema = getattr(agent, "output_schema", None)

    if output_schema is not None:
        llm = llm.with_structured_output(output_schema)

    react = create_agent(llm, tools)
    result = react.invoke(
        {"messages": [{"role": "system", "content": agent.persona},
                      {"role": "user", "content": str(input_data)}]}
    )

    # Extract the final AI message content.
    last_msg = result["messages"][-1]
    if output_schema is not None:
        # Structured output is attached to the last tool message or parsed content.
        return getattr(last_msg, "content", last_msg)
    return last_msg.content


def __orca_invoke_tool(tool: SimpleNamespace, input_data: Any) -> Any:
    """Invoke a tool node by calling its invoke callable directly."""
    return tool.invoke(input_data)


gpt4 = __orca_block("model", 
    provider_class=ChatOpenAI,
    model_name="gpt-4o",
)

researcher = __orca_block("agent", 
    model=gpt4,
    persona="You research topics thoroughly.",
)

writer = __orca_block("agent", 
    model=gpt4,
    persona="You write polished articles.",
)

daily = __orca_block("cron", 
    schedule="0 9 * * *",
)

hooks_in = __orca_block("webhook", 
    path="/hooks/in",
)

class __orca_state_pipeline(TypedDict):
    __orca_trigger: str | None
    __orca_payload: dict | None
    daily: Any
    researcher: Any
    writer: Any
    hooks_in: Any

def __orca_node_daily(state: __orca_state_pipeline) -> dict:
    """Workflow node wrapping 'daily'."""
    _predecessors = []
    _input = __orca_gather(state, _predecessors)
    raise NotImplementedError("workflow node "daily": block kind "cron" is not supported in workflows yet")
    return {"daily": _out}

def __orca_node_researcher(state: __orca_state_pipeline) -> dict:
    """Workflow node wrapping 'researcher'."""
    _predecessors = ["daily", "hooks_in"]
    _input = __orca_gather(state, _predecessors)
    _out = __orca_invoke_agent(researcher, _input)
    return {"researcher": _out}

def __orca_node_writer(state: __orca_state_pipeline) -> dict:
    """Workflow node wrapping 'writer'."""
    _predecessors = ["researcher"]
    _input = __orca_gather(state, _predecessors)
    _out = __orca_invoke_agent(writer, _input)
    return {"writer": _out}

def __orca_node_hooks_in(state: __orca_state_pipeline) -> dict:
    """Workflow node wrapping 'hooks_in'."""
    _predecessors = []
    _input = __orca_gather(state, _predecessors)
    raise NotImplementedError("workflow node "hooks_in": block kind "webhook" is not supported in workflows yet")
    return {"hooks_in": _out}

def __orca_route_pipeline(state: __orca_state_pipeline) -> str:
    """Route to entry node based on trigger source."""
    return ["daily", "hooks_in"]

pipeline = StateGraph(__orca_state_pipeline)
pipeline.add_node("daily", __orca_node_daily)
pipeline.add_node("researcher", __orca_node_researcher)
pipeline.add_node("writer", __orca_node_writer)
pipeline.add_node("hooks_in", __orca_node_hooks_in)
pipeline.add_conditional_edges(START, __orca_route_pipeline)
pipeline.add_edge("daily", "researcher")
pipeline.add_edge("researcher", "writer")
pipeline.add_edge("hooks_in", "researcher")
pipeline.add_edge("writer", END)
pipeline = pipeline.compile()

if __name__ == "__main__":
    payload = sys.argv[1] if len(sys.argv) >= 2 else ""
    initial_state: __orca_state_pipeline = {
        "__orca_trigger": "",
        "__orca_payload": payload,
        "daily": "",
        "researcher": "",
        "writer": "",
        "hooks_in": "",
    }
    final_state = pipeline.invoke(initial_state)
    print(final_state)
