# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

from langchain_openai import ChatOpenAI

from langgraph.graph import StateGraph, START, END

# --- Models ---

gpt4 = orca.model(
    provider="openai",
    model_name="gpt-4o",
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState

# --- Agents ---

classifier = orca.agent(
    model=gpt4,
    persona="You classify incoming requests.",
)

writer = orca.agent(
    model=gpt4,
    persona="You write content.",
)

analyst = orca.agent(
    model=gpt4,
    persona="You analyze data.",
)

reviewer = orca.agent(
    model=gpt4,
    persona="You review and merge results.",
)

# --- Workflows ---

def _node_classifier(state: GraphState) -> dict:
    """Workflow node wrapping 'classifier'."""
    pass  # TODO: implement node invocation for 'classifier'

def _node_writer(state: GraphState) -> dict:
    """Workflow node wrapping 'writer'."""
    pass  # TODO: implement node invocation for 'writer'

def _node_analyst(state: GraphState) -> dict:
    """Workflow node wrapping 'analyst'."""
    pass  # TODO: implement node invocation for 'analyst'

def _node_reviewer(state: GraphState) -> dict:
    """Workflow node wrapping 'reviewer'."""
    pass  # TODO: implement node invocation for 'reviewer'

diamond = StateGraph(GraphState)
diamond.add_node("classifier", _node_classifier)
diamond.add_node("writer", _node_writer)
diamond.add_node("analyst", _node_analyst)
diamond.add_node("reviewer", _node_reviewer)
diamond.add_edge(START, "classifier")
diamond.add_edge("classifier", "writer")
diamond.add_edge("classifier", "analyst")
diamond.add_edge("writer", "reviewer")
diamond.add_edge("analyst", "reviewer")
diamond.add_edge("reviewer", END)
diamond = diamond.compile()
