# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

from langchain_openai import ChatOpenAI

from tools.validation import check_style

from langgraph.graph import StateGraph, START, END

# --- Models ---

gpt4 = orca.model(
    provider="openai",
    model_name="gpt-4o",
)

# --- Tools ---

validate = orca.tool(
    desc="Validate report against style guide",
    invoke=check_style,
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState

# --- Agents ---

drafter = orca.agent(
    model=gpt4,
    persona="You draft reports.",
)

reviewer = orca.agent(
    model=gpt4,
    persona="You review validated reports.",
)

# --- Workflows ---

def _node_drafter(state: GraphState) -> dict:
    """Workflow node wrapping 'drafter'."""
    pass  # TODO: implement node invocation for 'drafter'

def _node_validate(state: GraphState) -> dict:
    """Workflow node wrapping 'validate'."""
    pass  # TODO: implement node invocation for 'validate'

def _node_reviewer(state: GraphState) -> dict:
    """Workflow node wrapping 'reviewer'."""
    pass  # TODO: implement node invocation for 'reviewer'

review_pipeline = StateGraph(GraphState)
review_pipeline.add_node("drafter", _node_drafter)
review_pipeline.add_node("validate", _node_validate)
review_pipeline.add_node("reviewer", _node_reviewer)
review_pipeline.add_edge(START, "drafter")
review_pipeline.add_edge("drafter", "validate")
review_pipeline.add_edge("validate", "reviewer")
review_pipeline.add_edge("reviewer", END)
review_pipeline = review_pipeline.compile()
