# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

from langchain_openai import ChatOpenAI

from langgraph.graph import StateGraph, START, END

# --- Models ---

gpt4 = orca.model(
    provider="openai",
    model_name="gpt-4o",
)

# --- Graph State ---
class GraphState(TypedDict):
    __orca_trigger__: str | None
    __orca_payload__: dict | None

# --- Agents ---

researcher = orca.agent(
    model=gpt4,
    persona="You research topics thoroughly.",
)

writer = orca.agent(
    model=gpt4,
    persona="You write polished articles.",
)

# --- Workflows ---

def _node_researcher(state: GraphState) -> dict:
    """Workflow node wrapping 'researcher'."""
    pass  # TODO: implement node invocation for 'researcher'

def _node_writer(state: GraphState) -> dict:
    """Workflow node wrapping 'writer'."""
    pass  # TODO: implement node invocation for 'writer'

def _route_pipeline(state: GraphState) -> str:
    """Route to entry node based on trigger source."""
    return "researcher"

pipeline = StateGraph(GraphState)
pipeline.add_node("researcher", _node_researcher)
pipeline.add_node("writer", _node_writer)
pipeline.add_conditional_edges(START, _route_pipeline)
pipeline.add_edge("researcher", "writer")
pipeline.add_edge("writer", END)
pipeline = pipeline.compile()
