# Auto-generated by Orca compiler — do not edit
import orca
from typing import TypedDict

from langchain_openai import ChatOpenAI

from langgraph.graph import StateGraph, START, END

# --- Models ---

gpt4 = orca.model(
    provider="openai",
    model_name="gpt-4o",
)

# --- Graph State ---
class GraphState(TypedDict):
    pass # TODO: writeGraphState

# --- Agents ---

researcher = orca.agent(
    model=gpt4,
    persona="You research topics thoroughly.",
)

writer = orca.agent(
    model=gpt4,
    persona="You write polished articles.",
)

# --- Cron ---

daily = orca.cron(
    schedule="0 9 * * *",
)

# --- Webhooks ---

hooks_in = orca.webhook(
    path="/hooks/in",
)

# --- Workflows ---

def _node_daily(state: GraphState) -> dict:
    """Workflow node wrapping 'daily'."""
    pass  # TODO: implement node invocation for 'daily'

def _node_researcher(state: GraphState) -> dict:
    """Workflow node wrapping 'researcher'."""
    pass  # TODO: implement node invocation for 'researcher'

def _node_writer(state: GraphState) -> dict:
    """Workflow node wrapping 'writer'."""
    pass  # TODO: implement node invocation for 'writer'

def _node_hooks_in(state: GraphState) -> dict:
    """Workflow node wrapping 'hooks_in'."""
    pass  # TODO: implement node invocation for 'hooks_in'

pipeline = StateGraph(GraphState)
pipeline.add_node("daily", _node_daily)
pipeline.add_node("researcher", _node_researcher)
pipeline.add_node("writer", _node_writer)
pipeline.add_node("hooks_in", _node_hooks_in)
pipeline.add_edge(START, "daily")
pipeline.add_edge(START, "hooks_in")
pipeline.add_edge("daily", "researcher")
pipeline.add_edge("researcher", "writer")
pipeline.add_edge("hooks_in", "researcher")
pipeline.add_edge("writer", END)
pipeline = pipeline.compile()
