# Auto-generated by Orca compiler — do not edit

from langchain_anthropic import ChatAnthropic

from langchain_google_genai import ChatGoogleGenerativeAI

from langchain_openai import ChatOpenAI


def _orca_build_chat_model(provider, model_name, *, temperature=None, api_key=None):
    """Instantiate the LangChain chat model for a runtime provider string."""
    kwargs = {"model": model_name}
    if temperature is not None:
        kwargs["temperature"] = temperature
    if provider == "openai":
        if api_key is not None:
            kwargs["api_key"] = api_key
        return ChatOpenAI(**kwargs)
    if provider == "anthropic":
        if api_key is not None:
            kwargs["api_key"] = api_key
        return ChatAnthropic(**kwargs)
    if provider == "google":
        if api_key is not None:
            kwargs["google_api_key"] = api_key
        return ChatGoogleGenerativeAI(**kwargs)
    raise ValueError(f"unknown provider: {provider!r}")

def parse_orca_inputs(argv=None):
    """Parse CLI arguments for Orca input blocks."""
    import argparse
    import json
    import os
    import types

    p = argparse.ArgumentParser()
    # line 1
    p.add_argument("--provider", required=True, help="LLM provider (e.g. openai).")
    # line 6
    p.add_argument("--model-name", required=True, help="Model name.")

    ns = p.parse_args(argv)

    return types.SimpleNamespace(
        provider=ns.provider,
        model_name=ns.model_name,
    )

def main(argv=None):
    args = parse_orca_inputs(argv)
    provider = args.provider
    model_name = args.model_name

    # --- Models ---

    llm = _orca_build_chat_model(  # line 11
        provider,
        model_name,
        temperature=0.2,
    )

    # --- Agents ---

    writer = create_react_agent(  # line 17
        llm,
        prompt="You are a helpful writer.",
    )


if __name__ == "__main__":
    main()
