# Auto-generated by Orca compiler — do not edit
"""Orca runtime — inlined into generated main.py.

These functions are called by generated code to create block instances.
All public names are prefixed with __orca_ to avoid collisions with user code.
"""

from __future__ import annotations

from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
import sys

from types import SimpleNamespace
from typing import Any, TypedDict

from langchain.agents import create_agent
from pydantic import BaseModel, create_model


def _orca__coerce_output_schema(schema: Any) -> tuple[type[BaseModel], bool]:
    """Ensure output_schema is a Pydantic model suitable for LLM structured output.

    LLM providers require the top-level response schema to be an object, so
    primitive/container types (str, list[int], dict[str, bool], etc.) are
    wrapped in a synthetic one-field model. Returns (model, wrapped) where
    wrapped=True means callers should read `.result` to unwrap.
    """
    if isinstance(schema, type) and issubclass(schema, BaseModel):
        return schema, False
    return create_model("_OrcaOutput", result=(schema, ...)), True


def _orca__block(kind: str, **kwargs: Any) -> SimpleNamespace:
    """Create a block instance with the given kind and keyword fields."""
    return SimpleNamespace(_kind=kind, **kwargs)


def _orca__fields(params: dict[str, Any]) -> dict[str, Any]:
    """Filter out None values from a parameter dict to omit unset optional fields."""
    return {k: v for k, v in params.items() if v is not None}


def _orca__meta(name: str, *args: Any) -> SimpleNamespace:
    """Single Orca decorator as data (@name or @name(args...))."""
    return SimpleNamespace(_kind="meta", name=name, args=args)


def _orca__with_meta(value: Any, metas: list[Any]) -> SimpleNamespace:
    """Attach a non-empty list of _orca__meta() values to a block or field value."""
    return SimpleNamespace(_kind="with_meta", value=value, metas=metas)

def _orca__gather(state: dict, predecessors: list[str]) -> Any:
    """Collect predecessor outputs from workflow state.

    No predecessors (entry nodes) use the _orca__payload field as input.
    Single predecessor returns its value directly.
    Multiple predecessors returns a dict keyed by predecessor name.
    """
    if len(predecessors) == 0:
        return state.get("_orca__payload")
    if len(predecessors) == 1:
        return state.get(predecessors[0])
    return {k: state.get(k) for k in predecessors}


# FIXME: This is ugly, but works for now, we need to do the provider registry
# and lookup properly.
def _orca__provider_from_name(provider: str) -> Any:
    if provider == "openai":
        import langchain_openai
        return langchain_openai.ChatOpenAI
    elif provider == "anthropic":
        import langchain_anthropic
        return langchain_anthropic.ChatAnthropic
    elif provider == "google":
        import langchain_google_genai
        return langchain_google_genai.ChatGoogleGenerativeAI
    else:
        raise ValueError(f"Unknown provider: {provider}")


def _orca__resolve_model(model_ns: SimpleNamespace, temperature_override: Any = None) -> Any:
    """Instantiate a LangChain ChatModel from a model SimpleNamespace.

    The provider_class field is the actual class (e.g. ChatOpenAI), resolved
    at compile time by the codegen. No runtime provider lookup needed.

    temperature_override, when not None, replaces the model block's
    temperature — used for per-agent overrides.
    """

    provider = getattr(model_ns, "provider", "openai")
    provider_class = _orca__provider_from_name(provider)

    temperature = temperature_override
    if temperature is None:
        temperature = getattr(model_ns, "temperature", None)

    return provider_class(**_orca__fields({
        "model": model_ns.model_name,
        "temperature": temperature,
        "api_key": getattr(model_ns, "api_key", None),
        "base_url": getattr(model_ns, "base_url", None),
    }))


def _orca__invoke_agent(agent: SimpleNamespace, input_data: Any) -> Any:
    """Invoke an agent node using create_agent (works with or without tools)."""
    llm = _orca__resolve_model(agent.model, getattr(agent, "temperature", None))
    tools = [t.invoke for t in getattr(agent, "tools", None) or []]
    output_schema = getattr(agent, "output_schema", None)

    kwargs = {}
    wrapped = False
    if output_schema is not None:
        model, wrapped = _orca__coerce_output_schema(output_schema)
        kwargs["response_format"] = model

    react = create_agent(llm, tools, **kwargs)
    messages = [{"role": "system", "content": agent.persona}]
    # Use input_data as user message, or default to "Proceed" if empty.
    user_content = str(input_data).strip() if input_data else ""
    if not user_content:
        user_content = "Proceed with the instructions provided."
    messages.append({"role": "user", "content": user_content})

    result = react.invoke({"messages": messages})

    if output_schema is not None:
        resp = result["structured_response"]
        return resp.result if wrapped else resp
    return result["messages"][-1].content


def _orca__invoke_tool(tool: SimpleNamespace, input_data: Any) -> Any:
    """Invoke a tool node by calling its invoke callable directly."""
    return tool.invoke(input_data)


gpt4 = _orca__block("model", 
    provider="openai",
    model_name="gpt-4o",
)

classifier = _orca__block("agent", 
    model=gpt4,
    persona="Classify as 'a' or 'b'.",
)

handler_a = _orca__block("agent", 
    model=gpt4,
    persona="Handle case A.",
)

handler_b1 = _orca__block("agent", 
    model=gpt4,
    persona="Handle B sub-case 1.",
)

handler_b2 = _orca__block("agent", 
    model=gpt4,
    persona="Handle B sub-case 2.",
)

class _orca__state_pipeline(TypedDict):
    _orca__trigger: str | None
    _orca__payload: dict | None
    classifier: Any
    _orca__anon_1: Any
    handler_a: Any
    _orca__anon_2: Any
    handler_b1: Any
    handler_b2: Any
    _orca__route___orca__anon_1: Any
    _orca__route___orca__anon_2: Any

def _orca__node_classifier(state: _orca__state_pipeline) -> dict:
    """Workflow node wrapping 'classifier'."""
    _predecessors = []
    _input = _orca__gather(state, _predecessors)
    _out = _orca__invoke_agent(classifier, _input)
    return {"classifier": _out}

def _orca__node__orca__anon_1(state: _orca__state_pipeline) -> dict:
    """Workflow node wrapping '_orca__anon_1'."""
    _predecessors = ["classifier"]
    _input = _orca__gather(state, _predecessors)
    _route_key = ((lambda out: out))(_input)
    return {"_orca__anon_1": _input, "_orca__route___orca__anon_1": _route_key}

def _orca__node_handler_a(state: _orca__state_pipeline) -> dict:
    """Workflow node wrapping 'handler_a'."""
    _predecessors = ["_orca__anon_1"]
    _input = _orca__gather(state, _predecessors)
    _out = _orca__invoke_agent(handler_a, _input)
    return {"handler_a": _out}

def _orca__node__orca__anon_2(state: _orca__state_pipeline) -> dict:
    """Workflow node wrapping '_orca__anon_2'."""
    _predecessors = ["_orca__anon_1"]
    _input = _orca__gather(state, _predecessors)
    _route_key = ((lambda out: out))(_input)
    return {"_orca__anon_2": _input, "_orca__route___orca__anon_2": _route_key}

def _orca__node_handler_b1(state: _orca__state_pipeline) -> dict:
    """Workflow node wrapping 'handler_b1'."""
    _predecessors = ["_orca__anon_2"]
    _input = _orca__gather(state, _predecessors)
    _out = _orca__invoke_agent(handler_b1, _input)
    return {"handler_b1": _out}

def _orca__node_handler_b2(state: _orca__state_pipeline) -> dict:
    """Workflow node wrapping 'handler_b2'."""
    _predecessors = ["_orca__anon_2"]
    _input = _orca__gather(state, _predecessors)
    _out = _orca__invoke_agent(handler_b2, _input)
    return {"handler_b2": _out}

def _orca__route_pipeline(state: _orca__state_pipeline) -> str:
    """Route to entry node based on trigger source."""
    return "classifier"

def _orca__route_pipeline_branch__orca__anon_1(state: _orca__state_pipeline) -> Any:
    """Branch router for "_orca__anon_1"."""
    _key = state.get("_orca__route___orca__anon_1", "default")
    if _key in {"a", "b"}:
        return _key
    return "default"

def _orca__route_pipeline_branch__orca__anon_2(state: _orca__state_pipeline) -> Any:
    """Branch router for "_orca__anon_2"."""
    _key = state.get("_orca__route___orca__anon_2", "default")
    if _key in {"1", "2"}:
        return _key
    return "default"

pipeline = StateGraph(_orca__state_pipeline)
pipeline.add_node("classifier", _orca__node_classifier)
pipeline.add_node("_orca__anon_1", _orca__node__orca__anon_1)
pipeline.add_node("handler_a", _orca__node_handler_a)
pipeline.add_node("_orca__anon_2", _orca__node__orca__anon_2)
pipeline.add_node("handler_b1", _orca__node_handler_b1)
pipeline.add_node("handler_b2", _orca__node_handler_b2)
pipeline.add_conditional_edges(START, _orca__route_pipeline)
pipeline.add_conditional_edges("_orca__anon_1", _orca__route_pipeline_branch__orca__anon_1, {"a": "handler_a", "b": "_orca__anon_2", "default": END})
pipeline.add_conditional_edges("_orca__anon_2", _orca__route_pipeline_branch__orca__anon_2, {"1": "handler_b1", "2": "handler_b2", "default": END})
pipeline.add_edge("classifier", "_orca__anon_1")
pipeline.add_edge("handler_a", END)
pipeline.add_edge("handler_b1", END)
pipeline.add_edge("handler_b2", END)
pipeline = pipeline.compile()

_orca__anon_1 = _orca__block("branch", 
    transform=(lambda out: out),
    route={"a": handler_a, "b": _orca__block("branch", transform=(lambda out: out), route={"1": handler_b1, "2": handler_b2}, )},
)

_orca__anon_2 = _orca__block("branch", 
    transform=(lambda out: out),
    route={"1": handler_b1, "2": handler_b2},
)

if __name__ == "__main__":
    payload = sys.argv[1] if len(sys.argv) >= 2 else ""
    initial_state: _orca__state_pipeline = {
        "_orca__trigger": "",
        "_orca__payload": payload,
        "classifier": "",
        "_orca__anon_1": "",
        "handler_a": "",
        "_orca__anon_2": "",
        "handler_b1": "",
        "handler_b2": "",
        "_orca__route___orca__anon_1": "",
        "_orca__route___orca__anon_2": "",
    }
    final_state = pipeline.invoke(initial_state)
    print(final_state)
