// Package codegen generates Python/LangGraph code from the IR.
// Produces main.py and pyproject.toml for a runnable build/ folder.
package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/thakee/orca/compiler/ast"
	"github.com/thakee/orca/compiler/ir"
)

// Output holds the generated files from codegen.
type Output struct {
	MainPy        string // generated Python source
	PyProjectTOML string // generated pyproject.toml
}

// Generate produces Python code and project config from the IR.
func Generate(program *ir.IR) Output {
	return Output{
		MainPy:        generateMain(program),
		PyProjectTOML: generatePyProject(program),
	}
}

func generateMain(program *ir.IR) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by Orca compiler — do not edit\n")
	writeImports(&b, program)

	if len(program.Lets) > 0 {
		b.WriteString("\n# --- Variables ---\n")
		for _, v := range program.Lets {
			b.WriteString("\n")
			writeLet(&b, v)
		}
	}

	if len(program.Models) > 0 {
		b.WriteString("\n# --- Models ---\n")
		for _, m := range program.Models {
			b.WriteString("\n")
			writeModel(&b, m)
		}
	}

	return b.String()
}

// providerImport maps a provider name to its langchain import statement.
var providerImport = map[string]string{
	"openai":    "from langchain_openai import ChatOpenAI",
	"anthropic": "from langchain_anthropic import ChatAnthropic",
	"google":    "from langchain_google_genai import ChatGoogleGenerativeAI",
}

// providerClass maps a provider name to its LangChain class name.
var providerClass = map[string]string{
	"openai":    "ChatOpenAI",
	"anthropic": "ChatAnthropic",
	"google":    "ChatGoogleGenerativeAI",
}

// providerDep maps provider names to pip package names.
var providerDep = map[string]string{
	"openai":    "langchain-openai",
	"anthropic": "langchain-anthropic",
	"google":    "langchain-google-genai",
}

func writeImports(b *strings.Builder, program *ir.IR) {
	// IR.Providers is pre-sorted.
	for _, p := range program.Providers {
		if imp, ok := providerImport[p]; ok {
			b.WriteString("\n")
			b.WriteString(imp)
			b.WriteString("\n")
		}
	}
}

func writeModel(b *strings.Builder, m ir.ModelDef) {
	// Unknown providers are caught by the analyzer — this is unreachable
	// in normal flow, but guard defensively.
	class := providerClass[m.Provider]
	if class == "" {
		return
	}

	var params []string
	params = append(params, fmt.Sprintf("model=%q", m.ModelName))
	if m.HasTemp {
		params = append(params, fmt.Sprintf("temperature=%s", formatFloat(m.Temperature)))
	}

	fmt.Fprintf(b, "%s = %s(%s)  # %s\n", m.Name, class, strings.Join(params, ", "), sourceComment(m.File, m.Line))
}

func writeLet(b *strings.Builder, v ir.LetVar) {
	fmt.Fprintf(b, "%s = %s  # %s\n", v.Name, exprToPython(v.Value), sourceComment(v.File, v.Line))
}

// exprToPython converts an AST expression to its Python representation.
func exprToPython(expr ast.Expression) string {
	switch e := expr.(type) {
	case *ast.StringLiteral:
		return fmt.Sprintf("%q", e.Value)
	case *ast.IntegerLiteral:
		return fmt.Sprintf("%d", e.Value)
	case *ast.FloatLiteral:
		return formatFloat(e.Value)
	case *ast.BooleanLiteral:
		if e.Value {
			return "True"
		}
		return "False"
	case *ast.NullLiteral:
		return "None"
	case *ast.Identifier:
		return e.Value
	case *ast.MemberAccess:
		return exprToPython(e.Object) + "." + e.Member
	case *ast.Subscription:
		return exprToPython(e.Object) + "[" + exprToPython(e.Index) + "]"
	case *ast.ListLiteral:
		var elems []string
		for _, el := range e.Elements {
			elems = append(elems, exprToPython(el))
		}
		return "[" + strings.Join(elems, ", ") + "]"
	case *ast.MapLiteral:
		var entries []string
		for _, entry := range e.Entries {
			entries = append(entries, exprToPython(entry.Key)+": "+exprToPython(entry.Value))
		}
		return "{" + strings.Join(entries, ", ") + "}"
	case *ast.BinaryExpression:
		return exprToPython(e.Left) + " " + e.Operator.Literal + " " + exprToPython(e.Right)
	case *ast.CallExpression:
		var args []string
		for _, arg := range e.Arguments {
			args = append(args, exprToPython(arg))
		}
		return exprToPython(e.Callee) + "(" + strings.Join(args, ", ") + ")"
	default:
		return "None"
	}
}

// sourceComment formats a source mapping comment like "agents.oc:42" or "line 42".
func sourceComment(file string, line int) string {
	if file != "" {
		return fmt.Sprintf("%s:%d", file, line)
	}
	return fmt.Sprintf("line %d", line)
}

// formatFloat formats a float without unnecessary trailing zeros,
// ensuring a decimal point for valid Python syntax.
func formatFloat(f float64) string {
	s := fmt.Sprintf("%g", f)
	if !strings.Contains(s, ".") && !strings.Contains(s, "e") {
		s += ".0"
	}
	return s
}

func generatePyProject(program *ir.IR) string {
	var b strings.Builder

	b.WriteString("[project]\n")
	b.WriteString("name = \"orca-build\"\n")
	b.WriteString("version = \"0.1.0\"\n")
	b.WriteString("requires-python = \">=3.11\"\n")
	b.WriteString("dependencies = [\n")
	b.WriteString("    \"langchain-core\",\n")

	deps := providerDeps(program.Providers)
	for _, dep := range deps {
		fmt.Fprintf(&b, "    %q,\n", dep)
	}

	b.WriteString("]\n")

	return b.String()
}

// providerDeps returns sorted, deduplicated pip dependencies.
func providerDeps(providers []string) []string {
	seen := make(map[string]bool)
	var deps []string
	for _, p := range providers {
		if dep, ok := providerDep[p]; ok && !seen[dep] {
			deps = append(deps, dep)
			seen[dep] = true
		}
	}
	sort.Strings(deps)
	return deps
}
