package langgraph

import (
	"strings"

	"github.com/thakee/orca/orca/compiler/codegen"
)

// FIXME: This is hardcoded, actually the entire codegen is hardcoded
// we need to do it properly, but the rule is make it work and make it work properly.
//
// pyprojectToml returns a minimal PEP 621 pyproject.toml capturing all runtime deps.
// This file is generated into build/ so users can `pip install -e build/` or
// use uv/poetry tooling without manually copying dependencies.
func pyprojectToml(deps []codegen.Dependency) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by Orca compiler — do not edit\n\n")

	b.WriteString("[project]\n")
	b.WriteString("name = \"orca-build\"\n")
	b.WriteString("version = \"0.1.0\"\n")
	b.WriteString("requires-python = \">=3.11\"\n")
	b.WriteString("dependencies = [\n")
	for _, dep := range deps {
		if dep.DevDependency {
			continue
		}
		if dep.MinVersion != "" {
			b.WriteString("  \"")
			b.WriteString(dep.Name)
			b.WriteString(">=")
			b.WriteString(dep.MinVersion)
			b.WriteString("\",\n")
			continue
		}
		b.WriteString("  \"")
		b.WriteString(dep.Name)
		b.WriteString("\",\n")
	}
	b.WriteString("]\n\n")

	b.WriteString("[build-system]\n")
	b.WriteString("requires = [\"hatchling\"]\n")
	b.WriteString("build-backend = \"hatchling.build\"\n")

	b.WriteString("\n[tool.hatch.build.targets.wheel]\n")
	b.WriteString("only-include = [\"main.py\"]\n")
	b.WriteString("sources = [\".\"]\n")

	return b.String()
}
